clc
close all
clear all %#ok<CLALL>
format longG
pathStr = genpath('dependencies');
addpath(pathStr);
tic

AreaCx3(1) = area(5.644, 5.644);
AreaCx3(2) = area(5.644, 160*5.644);
AreaTC = area(60, 90);
AreaNRT = area(42, 63);

list = dir('*dat');
iList = 001:900;

dt = .25;
%dtInterpInit = 10*dt;
dtInterpInit = 40*dt;
dtInterpFinal = 40*dt;
xRange = [015000 1200000]+dt;
nPY = 100;
nIN = 50;
nTC = 100;
nNRT = 50;
nCores = 4;
fullRun = true;
loadSpikes = false;
voltage = false;
spiking = true;
type = 'SWDs';
psiWindow = round(1000/dtInterpInit);

iRange = xRange./dt;
iRange = round(iRange(1):iRange(end));
combosPY = nchoosek(1:nPY,2);
combosIN = nchoosek(1:nIN,2);
combosTC = nchoosek(1:nTC,2);
combosNRT = nchoosek(1:nNRT,2);

% Load the EEG data
EEGinit = readBinary('EEG.bin', 'double');

% Estimate EEG oscillation frequency and band-pass filter the EEG data
oscFrequency = oscFreq(EEGinit, dt, type);
Fpass = [oscFrequency-4; oscFrequency-2; oscFrequency; oscFrequency+2; oscFrequency+4];
Fpass(Fpass <= 0) = 1e-9;
if exist('filter.mat', 'file')
    load('filter.mat'); %#ok<*LOAD>
else
    d = designFilterBP(Fpass, 65, 0.5, 65, 1000/dt);
end
EEGinitFilt = filtfilt(d, EEGinit);
[~, phaseEEGinitHT] = hilbertTransform(EEGinitFilt-mean(EEGinitFilt));

% Detect EEG spikes
if strcmpi(type, 'SWDs')
    [eegSpikes, eegSpikesSWD, eegSpikesT, eegSpikesLocs, eegSpikesLocsSWD, eegSpikesLarge, eegSpikesLargeSWD,...
        eegSpikesLargeT, eegSpikesLargeLocs, eegSpikesLargeLocsSWD, tWaves, waveLocs, tWavesLarge, waveLocsLarge, SWDs,...
        SWDsLarge, phase, SWCs, phaseLarge, SWCsLarge, interictal, interictalLarge] = detectEEGspikesSWDs(EEGinit(iRange), dt, true); %#ok<*ASGLU>
else
    eegSpikes = detectEEGspikes(EEGinit(iRange), dt, type);
end

%% Calculate coherence
if fullRun
    
    % Initialise variables
    [~, data1] = loadFile(list(1).name, AreaCx3, 'Cx3');
    t = data1.t(iRange);
    tInterpInit = t(1):dtInterpInit:t(end);
    tInterpFinal = t(1):dtInterpFinal:t(end);
    vTC = zeros(nTC, length(tInterpInit));
    vNRT = zeros(nNRT, length(tInterpInit));
    vTC2 = vTC;
    vNRT2 = vNRT;
    vCx23 = zeros(nPY, length(tInterpInit));
    vCx23i = zeros(nIN, length(tInterpInit));
    vCx4 = vCx23;
    vCx4i = vCx23i;
    vCx5 = vCx23;
    vCx5i = vCx23i;
    vCx6 = vCx23;
    vCx6i = vCx23i;
    vAll = zeros(numel(iList), length(tInterpInit));
    
    rasterTC = zeros(nTC, length(tInterpInit));
    rasterNRT = zeros(nNRT, length(tInterpInit));
    rasterTC2 = rasterTC;
    rasterNRT2 = rasterNRT;
    rasterCx23 = zeros(nPY, length(tInterpInit));
    rasterCx23i = zeros(nIN, length(tInterpInit));
    rasterCx4 = rasterCx23;
    rasterCx4i = rasterCx23i;
    rasterCx5 = rasterCx23;
    rasterCx5i = rasterCx23i;
    rasterCx6 = rasterCx23;
    rasterCx6i = rasterCx23i;
    rasterAll = zeros(numel(iList), length(tInterpInit));
    
    parpool(nCores);
    parfor l = iList
    %for l = iList
        if voltage || (spiking && ~loadSpikes)
            disp(['Loading file: ' num2str(l)])
            fileName = list(l).name;
            if l <= 4*(nPY+nIN)
                [~, data, cellType] = loadFile(fileName, AreaCx3, 'Cx3');
            elseif l <= 4*(nPY+nIN)+2*nNRT
                [~, data, cellType] = loadFile(fileName, AreaNRT, 'NRT');
            elseif l <= 4*(nPY+nIN)+2*nNRT+2*nTC
                [~, data, cellType] = loadFile(fileName, AreaTC, 'TC');
            end
        end
        
        if voltage
            vAll(l,:) = interp1(t, data.v(iRange), tInterpInit);
        end
        if spiking && ~loadSpikes
            rasterAll(l,:) = interplAPs(t, rastergram(data.v(iRange)), tInterpInit);
        end
    end
    if spiking && loadSpikes
        load('spikingMat_loc.mat')
        rasterAll = full(rasterAll);
    elseif spiking && ~loadSpikes
        save('spikingMat_loc.mat', 'rasterAll', '-v7.3');
    end
    
    for l = iList
        if voltage
            if l >= 1 && l <= nPY
                vCx23(l,:) = vAll(l,:);
            elseif l >= nPY+1 && l <= nPY+nIN
                vCx23i(l-nPY,:) = vAll(l,:);
            elseif l >= nPY+nIN && l <= 2*nPY+nIN
                vCx4(l-(nPY+nIN),:) = vAll(l,:);
            elseif l >= 2*nPY+nIN+1 && l <= 2*nPY+2*nIN
                vCx4i(l-(2*nPY+nIN),:) = vAll(l,:);
            elseif l >= 2*nPY+2*nIN+1 && l <= 3*nPY+2*nIN
                vCx5(l-(2*nPY+2*nIN),:) = vAll(l,:);
            elseif l >= 3*nPY+2*nIN+1 && l <= 3*nPY+3*nIN
                vCx5i(l-(3*nPY+2*nIN),:) = vAll(l,:);
            elseif l >= 3*nPY+3*nIN+1 && l <= 4*nPY+3*nIN
                vCx6(l-(3*nPY+3*nIN),:) = vAll(l,:);
            elseif l >= 4*nPY+3*nIN+1 && l <= 4*nPY+4*nIN
                vCx6i(l-(4*nPY+3*nIN),:) = vAll(l,:);
            elseif l >= 4*nPY+4*nIN+1 && l <= 4*nPY+4*nIN+nNRT
                vNRT(l-(4*nPY+4*nIN),:) = vAll(l,:);
            elseif l >= 4*nPY+4*nIN+nNRT+1 && l <= 4*nPY+4*nIN+2*nNRT
                vNRT2(l-(4*nPY+4*nIN+nNRT),:) = vAll(l,:);
            elseif l >= 4*nPY+4*nIN+2*nNRT+1 && l <= 4*nPY+4*nIN+2*nNRT+nTC
                vTC(l-(4*nPY+4*nIN+2*nNRT),:) = vAll(l,:);
            elseif l >= 4*nPY+4*nIN+2*nNRT+nTC+1 && l <= 4*nPY+4*nIN+2*nNRT+2*nTC
                vTC2(l-(4*nPY+4*nIN+2*nNRT+nTC),:) = vAll(l,:);
            end
        end
        if spiking
            if l >= 1 && l <= nPY
                rasterCx23(l,:) = rasterAll(l,:);
            elseif l >= nPY+1 && l <= nPY+nIN
                rasterCx23i(l-nPY,:) = rasterAll(l,:);
            elseif l >= nPY+nIN && l <= 2*nPY+nIN
                rasterCx4(l-(nPY+nIN),:) = rasterAll(l,:);
            elseif l >= 2*nPY+nIN+1 && l <= 2*nPY+2*nIN
                rasterCx4i(l-(2*nPY+nIN),:) = rasterAll(l,:);
            elseif l >= 2*nPY+2*nIN+1 && l <= 3*nPY+2*nIN
                rasterCx5(l-(2*nPY+2*nIN),:) = rasterAll(l,:);
            elseif l >= 3*nPY+2*nIN+1 && l <= 3*nPY+3*nIN
                rasterCx5i(l-(3*nPY+2*nIN),:) = rasterAll(l,:);
            elseif l >= 3*nPY+3*nIN+1 && l <= 4*nPY+3*nIN
                rasterCx6(l-(3*nPY+3*nIN),:) = rasterAll(l,:);
            elseif l >= 4*nPY+3*nIN+1 && l <= 4*nPY+4*nIN
                rasterCx6i(l-(4*nPY+3*nIN),:) = rasterAll(l,:);
            elseif l >= 4*nPY+4*nIN+1 && l <= 4*nPY+4*nIN+nNRT
                rasterNRT(l-(4*nPY+4*nIN),:) = rasterAll(l,:);
            elseif l >= 4*nPY+4*nIN+nNRT+1 && l <= 4*nPY+4*nIN+2*nNRT
                rasterNRT2(l-(4*nPY+4*nIN+nNRT),:) = rasterAll(l,:);
            elseif l >= 4*nPY+4*nIN+2*nNRT+1 && l <= 4*nPY+4*nIN+2*nNRT+nTC
                rasterTC(l-(4*nPY+4*nIN+2*nNRT),:) = rasterAll(l,:);
            elseif l >= 4*nPY+4*nIN+2*nNRT+nTC+1 && l <= 4*nPY+4*nIN+2*nNRT+2*nTC
                rasterTC2(l-(4*nPY+4*nIN+2*nNRT+nTC),:) = rasterAll(l,:);
            end
        end
    end
    
    clear vAll rasterAll
    
    % Initialise variables
    if voltage
        psiCx23 = zeros(size(combosPY,1), 1);
        psiCx23i = zeros(size(combosIN,1), 1);
        psiCx4 = zeros(size(combosPY,1), 1);
        psiCx4i = zeros(size(combosIN,1), 1);
        psiCx5 = zeros(size(combosPY,1), 1);
        psiCx5i = zeros(size(combosIN,1), 1);
        psiCx6 = zeros(size(combosPY,1), 1);
        psiCx6i = zeros(size(combosIN,1), 1);
        psiNRT = zeros(size(combosNRT,1), 1);
        psiNRT2 = zeros(size(combosNRT,1), 1);
        psiTC = zeros(size(combosTC,1), 1);
        psiTC2 = zeros(size(combosTC,1), 1);
        psiCx23_t = zeros(size(combosPY,1), length(tInterpFinal));
        psiCx23i_t = zeros(size(combosIN,1), length(tInterpFinal));
        psiCx4_t = zeros(size(combosPY,1), length(tInterpFinal));
        psiCx4i_t = zeros(size(combosIN,1), length(tInterpFinal));
        psiCx5_t = zeros(size(combosPY,1), length(tInterpFinal));
        psiCx5i_t = zeros(size(combosIN,1), length(tInterpFinal));
        psiCx6_t = zeros(size(combosPY,1), length(tInterpFinal));
        psiCx6i_t = zeros(size(combosIN,1), length(tInterpFinal));
        psiNRT_t = zeros(size(combosNRT,1), length(tInterpFinal));
        psiNRT2_t = zeros(size(combosNRT,1), length(tInterpFinal));
        psiTC_t = zeros(size(combosTC,1), length(tInterpFinal));
        psiTC2_t = zeros(size(combosTC,1), length(tInterpFinal));
    end
    if spiking
        psiRasterCx23 = zeros(size(combosPY,1), 1);
        psiRasterCx23i = zeros(size(combosIN,1), 1);
        psiRasterCx4 = zeros(size(combosPY,1), 1);
        psiRasterCx4i = zeros(size(combosIN,1), 1);
        psiRasterCx5 = zeros(size(combosPY,1), 1);
        psiRasterCx5i = zeros(size(combosIN,1), 1);
        psiRasterCx6 = zeros(size(combosPY,1), 1);
        psiRasterCx6i = zeros(size(combosIN,1), 1);
        psiRasterNRT = zeros(size(combosNRT,1), 1);
        psiRasterNRT2 = zeros(size(combosNRT,1), 1);
        psiRasterTC = zeros(size(combosTC,1), 1);
        psiRasterTC2 = zeros(size(combosTC,1), 1);
        psiRasterCx23_t = zeros(size(combosPY,1), length(tInterpFinal));
        psiRasterCx23i_t = zeros(size(combosIN,1), length(tInterpFinal));
        psiRasterCx4_t = zeros(size(combosPY,1), length(tInterpFinal));
        psiRasterCx4i_t = zeros(size(combosIN,1), length(tInterpFinal));
        psiRasterCx5_t = zeros(size(combosPY,1), length(tInterpFinal));
        psiRasterCx5i_t = zeros(size(combosIN,1), length(tInterpFinal));
        psiRasterCx6_t = zeros(size(combosPY,1), length(tInterpFinal));
        psiRasterCx6i_t = zeros(size(combosIN,1), length(tInterpFinal));
        psiRasterNRT_t = zeros(size(combosNRT,1), length(tInterpFinal));
        psiRasterNRT2_t = zeros(size(combosNRT,1), length(tInterpFinal));
        psiRasterTC_t = zeros(size(combosTC,1), length(tInterpFinal));
        psiRasterTC2_t = zeros(size(combosTC,1), length(tInterpFinal));
    end
    
    cell1 = [];
    cell2 = [];
    vFilt = [];
    vFiltNorm = [];
    vFilt2 = [];
    vFiltNorm2 = [];
    rasterFilt = [];
    rasterFiltNorm = [];
    rasterFilt2 = [];
    rasterFiltNorm2 = [];
    psi_t = [];
    %for iCombo = 1:max([size(combosPY,1) size(combosIN,1) size(combosNRT,1) size(combosTC,1)])
    parfor iCombo = 1:max([size(combosPY,1) size(combosIN,1) size(combosNRT,1) size(combosTC,1)])
        disp(['Processing combo: ' num2str(iCombo)])
        
        % Membrane potential
        if voltage
            if iCombo <= size(combosPY,1)
                cell1 = combosPY(iCombo,1);
                cell2 = combosPY(iCombo,2);
                
                vFilt = filtfilt(d, vCx23(cell1,:)); %#ok<*PFBNS>
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vCx23(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiCx23(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiCx23_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                vFilt = filtfilt(d, vCx4(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vCx4(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiCx4(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiCx4_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                vFilt = filtfilt(d, vCx5(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vCx5(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiCx5(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiCx5_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                vFilt = filtfilt(d, vCx6(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vCx6(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiCx6(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiCx6_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
            end
            
            if iCombo <= size(combosIN,1)
                cell1 = combosIN(iCombo,1);
                cell2 = combosIN(iCombo,2);
                
                vFilt = filtfilt(d, vCx23i(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vCx23i(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiCx23i(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiCx23i_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                vFilt = filtfilt(d, vCx4i(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vCx4i(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiCx4i(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiCx4i_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                vFilt = filtfilt(d, vCx5i(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vCx5i(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiCx5i(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiCx5i_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                vFilt = filtfilt(d, vCx6i(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vCx6i(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiCx6i(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiCx6i_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
            end
            
            if iCombo <= size(combosNRT,1)
                cell1 = combosNRT(iCombo,1);
                cell2 = combosNRT(iCombo,2);
                
                vFilt = filtfilt(d, vNRT(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vNRT(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiNRT(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiNRT_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                vFilt = filtfilt(d, vNRT2(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vNRT2(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiNRT2(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiNRT2_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
            end
            
            if iCombo <= size(combosTC,1)
                cell1 = combosTC(iCombo,1);
                cell2 = combosTC(iCombo,2);
                
                vFilt = filtfilt(d, vTC(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vTC(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiTC(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiTC_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                vFilt = filtfilt(d, vTC2(cell1,:));
                vFiltNorm = (vFilt-min(vFilt))./max(vFilt-min(vFilt));
                vFilt2 = filtfilt(d, vTC2(cell2,:));
                vFiltNorm2 = (vFilt2-min(vFilt2))./max(vFilt2-min(vFilt2));
                [psiTC2(iCombo), psi_t] = hilbertPhaseSync(vFiltNorm, vFiltNorm2, psiWindow);
                psiTC2_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
            end
        end
        
        % Cell spiking
        if spiking
            if iCombo <= size(combosPY,1)
                cell1 = combosPY(iCombo,1);
                cell2 = combosPY(iCombo,2);
                
                rasterFilt = filtfilt(d, full(rasterCx23(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterCx23(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterCx23(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterCx23_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                rasterFilt = filtfilt(d, full(rasterCx4(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterCx4(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterCx4(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterCx4_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                rasterFilt = filtfilt(d, full(rasterCx5(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterCx5(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterCx5(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterCx5_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                rasterFilt = filtfilt(d, full(rasterCx6(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterCx6(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterCx6(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterCx6_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
            end
            
            if iCombo <= size(combosIN,1)
                cell1 = combosIN(iCombo,1);
                cell2 = combosIN(iCombo,2);
                
                rasterFilt = filtfilt(d, full(rasterCx23i(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterCx23i(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterCx23i(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterCx23i_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                rasterFilt = filtfilt(d, full(rasterCx4i(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterCx4i(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterCx4i(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterCx4i_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                rasterFilt = filtfilt(d, full(rasterCx5i(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterCx5i(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterCx5i(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterCx5i_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                rasterFilt = filtfilt(d, full(rasterCx6i(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterCx6i(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterCx6i(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterCx6i_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
            end
            
            if iCombo <= size(combosNRT,1)
                cell1 = combosNRT(iCombo,1);
                cell2 = combosNRT(iCombo,2);
                
                rasterFilt = filtfilt(d, full(rasterNRT(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterNRT(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterNRT(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterNRT_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                rasterFilt = filtfilt(d, full(rasterNRT2(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterNRT2(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterNRT2(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterNRT2_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
            end
            
            if iCombo <= size(combosTC,1)
                cell1 = combosTC(iCombo,1);
                cell2 = combosTC(iCombo,2);
                
                rasterFilt = filtfilt(d, full(rasterTC(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterTC(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterTC(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterTC_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
                
                rasterFilt = filtfilt(d, full(rasterTC2(cell1,:)));
                rasterFiltNorm = (rasterFilt-min(rasterFilt))./max(rasterFilt-min(rasterFilt));
                rasterFilt2 = filtfilt(d, full(rasterTC2(cell2,:)));
                rasterFiltNorm2 = (rasterFilt2-min(rasterFilt2))./max(rasterFilt2-min(rasterFilt2));
                [psiRasterTC2(iCombo), psi_t] = hilbertPhaseSync(rasterFiltNorm, rasterFiltNorm2, psiWindow);
                psiRasterTC2_t(iCombo,:) = interp1(tInterpInit, psi_t, tInterpFinal);
            end
        end
    end
    
    if voltage
        [psi2Cx23mean, psi2Cx23CI95] = datamean(psiCx23);
        [psi2Cx23imean, psi2Cx23iCI95] = datamean(psiCx23i);
        [psi2Cx4mean, psi2Cx4CI95] = datamean(psiCx4);
        [psi2Cx4imean, psi2Cx4iCI95] = datamean(psiCx4i);
        [psi2Cx5mean, psi2Cx5CI95] = datamean(psiCx5);
        [psi2Cx5imean, psi2Cx5iCI95] = datamean(psiCx5i);
        [psi2Cx6mean, psi2Cx6CI95] = datamean(psiCx6);
        [psi2Cx6imean, psi2Cx6iCI95] = datamean(psiCx6i);
        [psi2NRTmean, psi2NRTCI95] = datamean(psiNRT);
        [psi2NRT2mean, psi2NRT2CI95] = datamean(psiNRT2);
        [psi2TCmean, psi2TCCI95] = datamean(psiTC);
        [psi2TC2mean, psi2TC2CI95] = datamean(psiTC2);
    end
    
    if spiking
        [psi2RasterCx23mean, psi2RasterCx23CI95] = datamean(psiRasterCx23);
        [psi2RasterCx23imean, psi2RasterCx23iCI95] = datamean(psiRasterCx23i);
        [psi2RasterCx4mean, psi2RasterCx4CI95] = datamean(psiRasterCx4);
        [psi2RasterCx4imean, psi2RasterCx4iCI95] = datamean(psiRasterCx4i);
        [psi2RasterCx5mean, psi2RasterCx5CI95] = datamean(psiRasterCx5);
        [psi2RasterCx5imean, psi2RasterCx5iCI95] = datamean(psiRasterCx5i);
        [psi2RasterCx6mean, psi2RasterCx6CI95] = datamean(psiRasterCx6);
        [psi2RasterCx6imean, psi2RasterCx6iCI95] = datamean(psiRasterCx6i);
        [psi2RasterNRTmean, psi2RasterNRTCI95] = datamean(psiRasterNRT);
        [psi2RasterNRT2mean, psi2RasterNRT2CI95] = datamean(psiRasterNRT2);
        [psi2RasterTCmean, psi2RasterTCCI95] = datamean(psiRasterTC);
        [psi2RasterTC2mean, psi2RasterTC2CI95] = datamean(psiRasterTC2);
    end
    
    clear vTC rasterTC vNRT rasterNRT vTC2 rasterTC2 vNRT2 rasterNRT2 vCx23 rasterCx23 vCx23i rasterCx23i
    clear vCx4 rasterCx4 vCx4i rasterCx4i vCx5 rasterCx5 vCx5i rasterCx5i vCx6 rasterCx6 vCx6i rasterCx6i
end

save('vars.mat','-v7.3');
%% Average coherence over all SWDs
if fullRun
    SWDsInterp = interp1(t, SWDs, tInterpFinal, 'linear', 'extrap');
    SWDsLargeInterp = interp1(t, SWDsLarge, tInterpFinal, 'linear', 'extrap');
    interictalInterp = interp1(t, interictal, tInterpFinal, 'linear', 'extrap');
    interictalLargeInterp = interp1(t, interictalLarge, tInterpFinal, 'linear', 'extrap');
    if voltage
        disp('Processing voltage PSIs')
        [psi2Cx23MeanAligned, psi2Cx23CI95Aligned, tStartAligned, tEndAligned,...
            psi2Cx23MeanAlignedScaled, psi2Cx23CI95AlignedScaled, tStartAlignedScaled, tEndAlignedScaled,...
            psi2Cx23Mean_SWDs, psi2Cx23CI95_SWDs] = frAlign(SWDsInterp, psiCx23_t, tInterpFinal);
        [psi2Cx23MeanAlignedLarge, psi2Cx23CI95AlignedLarge, tStartAlignedLarge, tEndAlignedLarge,...
            psi2Cx23MeanAlignedScaledLarge, psi2Cx23CI95AlignedScaledLarge, tStartAlignedScaledLarge, tEndAlignedScaledLarge,...
            psi2Cx23MeanLarge_SWDs, psi2Cx23CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiCx23_t, tInterpFinal);
        [psi2Cx23iMeanAligned, psi2Cx23iCI95Aligned, ~, ~,...
            psi2Cx23iMeanAlignedScaled, psi2Cx23iCI95AlignedScaled, ~, ~,...
            psi2Cx23iMean_SWDs, psi2Cx23iCI95_SWDs] = frAlign(SWDsInterp, psiCx23i_t, tInterpFinal);
        [psi2Cx23iMeanAlignedLarge, psi2Cx23iCI95AlignedLarge, ~, ~,...
            psi2Cx23iMeanAlignedScaledLarge, psi2Cx23iCI95AlignedScaledLarge, ~, ~,...
            psi2Cx23iMeanLarge_SWDs, psi2Cx23iCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiCx23i_t, tInterpFinal);
        [psi2Cx4MeanAligned, psi2Cx4CI95Aligned, ~, ~,...
            psi2Cx4MeanAlignedScaled, psi2Cx4CI95AlignedScaled, ~, ~,...
            psi2Cx4Mean_SWDs, psi2Cx4CI95_SWDs] = frAlign(SWDsInterp, psiCx4_t, tInterpFinal);
        [psi2Cx4MeanAlignedLarge, psi2Cx4CI95AlignedLarge, ~, ~,...
            psi2Cx4MeanAlignedScaledLarge, psi2Cx4CI95AlignedScaledLarge, ~, ~,...
            psi2Cx4MeanLarge_SWDs, psi2Cx4CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiCx4_t, tInterpFinal);
        [psi2Cx4iMeanAligned, psi2Cx4iCI95Aligned, ~, ~,...
            psi2Cx4iMeanAlignedScaled, psi2Cx4iCI95AlignedScaled, ~, ~,...
            psi2Cx4iMean_SWDs, psi2Cx4iCI95_SWDs] = frAlign(SWDsInterp, psiCx4i_t, tInterpFinal);
        [psi2Cx4iMeanAlignedLarge, psi2Cx4iCI95AlignedLarge, ~, ~,...
            psi2Cx4iMeanAlignedScaledLarge, psi2Cx4iCI95AlignedScaledLarge, ~, ~,...
            psi2Cx4iMeanLarge_SWDs, psi2Cx4iCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiCx4i_t, tInterpFinal);
        [psi2Cx5MeanAligned, psi2Cx5CI95Aligned, ~, ~,...
            psi2Cx5MeanAlignedScaled, psi2Cx5CI95AlignedScaled, ~, ~,...
            psi2Cx5Mean_SWDs, psi2Cx5CI95_SWDs] = frAlign(SWDsInterp, psiCx5_t, tInterpFinal);
        [psi2Cx5MeanAlignedLarge, psi2Cx5CI95AlignedLarge, ~, ~,...
            psi2Cx5MeanAlignedScaledLarge, psi2Cx5CI95AlignedScaledLarge, ~, ~,...
            psi2Cx5MeanLarge_SWDs, psi2Cx5CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiCx5_t, tInterpFinal);
        [psi2Cx5iMeanAligned, psi2Cx5iCI95Aligned, ~, ~,...
            psi2Cx5iMeanAlignedScaled, psi2Cx5iCI95AlignedScaled, ~, ~,...
            psi2Cx5iMean_SWDs, psi2Cx5iCI95_SWDs] = frAlign(SWDsInterp, psiCx5i_t, tInterpFinal);
        [psi2Cx5iMeanAlignedLarge, psi2Cx5iCI95AlignedLarge, ~, ~,...
            psi2Cx5iMeanAlignedScaledLarge, psi2Cx5iCI95AlignedScaledLarge, ~, ~,...
            psi2Cx5iMeanLarge_SWDs, psi2Cx5iCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiCx5i_t, tInterpFinal);
        [psi2Cx6MeanAligned, psi2Cx6CI95Aligned, ~, ~,...
            psi2Cx6MeanAlignedScaled, psi2Cx6CI95AlignedScaled, ~, ~,...
            psi2Cx6Mean_SWDs, psi2Cx6CI95_SWDs] = frAlign(SWDsInterp, psiCx6_t, tInterpFinal);
        [psi2Cx6MeanAlignedLarge, psi2Cx6CI95AlignedLarge, ~, ~,...
            psi2Cx6MeanAlignedScaledLarge, psi2Cx6CI95AlignedScaledLarge, ~, ~,...
            psi2Cx6MeanLarge_SWDs, psi2Cx6CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiCx6_t, tInterpFinal);
        [psi2Cx6iMeanAligned, psi2Cx6iCI95Aligned, ~, ~,...
            psi2Cx6iMeanAlignedScaled, psi2Cx6iCI95AlignedScaled, ~, ~,...
            psi2Cx6iMean_SWDs, psi2Cx6iCI95_SWDs] = frAlign(SWDsInterp, psiCx6i_t, tInterpFinal);
        [psi2Cx6iMeanAlignedLarge, psi2Cx6iCI95AlignedLarge, ~, ~,...
            psi2Cx6iMeanAlignedScaledLarge, psi2Cx6iCI95AlignedScaledLarge, ~, ~,...
            psi2Cx6iMeanLarge_SWDs, psi2Cx6iCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiCx6i_t, tInterpFinal);
        [psi2NRTMeanAligned, psi2NRTCI95Aligned, ~, ~,...
            psi2NRTMeanAlignedScaled, psi2NRTCI95AlignedScaled, ~, ~,...
            psi2NRTMean_SWDs, psi2NRTCI95_SWDs] = frAlign(SWDsInterp, psiNRT_t, tInterpFinal);
        [psi2NRTMeanAlignedLarge, psi2NRTCI95AlignedLarge, ~, ~,...
            psi2NRTMeanAlignedScaledLarge, psi2NRTCI95AlignedScaledLarge, ~, ~,...
            psi2NRTMeanLarge_SWDs, psi2NRTCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiNRT_t, tInterpFinal);
        [psi2NRT2MeanAligned, psi2NRT2CI95Aligned, ~, ~,...
            psi2NRT2MeanAlignedScaled, psi2NRT2CI95AlignedScaled, ~, ~,...
            psi2NRT2Mean_SWDs, psi2NRT2CI95_SWDs] = frAlign(SWDsInterp, psiNRT2_t, tInterpFinal);
        [psi2NRT2MeanAlignedLarge, psi2NRT2CI95AlignedLarge, ~, ~,...
            psi2NRT2MeanAlignedScaledLarge, psi2NRT2CI95AlignedScaledLarge, ~, ~,...
            psi2NRT2MeanLarge_SWDs, psi2NRT2CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiNRT2_t, tInterpFinal);
        [psi2TCMeanAligned, psi2TCCI95Aligned, ~, ~,...
            psi2TCMeanAlignedScaled, psi2TCCI95AlignedScaled, ~, ~,...
            psi2TCMean_SWDs, psi2TCCI95_SWDs] = frAlign(SWDsInterp, psiTC_t, tInterpFinal);
        [psi2TCMeanAlignedLarge, psi2TCCI95AlignedLarge, ~, ~,...
            psi2TCMeanAlignedScaledLarge, psi2TCCI95AlignedScaledLarge, ~, ~,...
            psi2TCMeanLarge_SWDs, psi2TCCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiTC_t, tInterpFinal);
        [psi2TC2MeanAligned, psi2TC2CI95Aligned, ~, ~,...
            psi2TC2MeanAlignedScaled, psi2TC2CI95AlignedScaled, ~, ~,...
            psi2TC2Mean_SWDs, psi2TC2CI95_SWDs] = frAlign(SWDsInterp, psiTC2_t, tInterpFinal);
        [psi2TC2MeanAlignedLarge, psi2TC2CI95AlignedLarge, ~, ~,...
            psi2TC2MeanAlignedScaledLarge, psi2TC2CI95AlignedScaledLarge, ~, ~,...
            psi2TC2MeanLarge_SWDs, psi2TC2CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiTC2_t, tInterpFinal);
        
        [psi2Cx23MeanAligned_i, psi2Cx23CI95Aligned_i, tStartAligned_i, tEndAligned_i,...
            psi2Cx23MeanAlignedScaled_i, psi2Cx23CI95AlignedScaled_i, tStartAlignedScaled_i, tEndAlignedScaled_i,...
            psi2Cx23Mean_interictal, psi2Cx23CI95_interictal] = frAlign(interictalInterp, psiCx23_t, tInterpFinal);
        [psi2Cx23MeanAlignedLarge_i, psi2Cx23CI95AlignedLarge_i, tStartAlignedLarge_i, tEndAlignedLarge_i,...
            psi2Cx23MeanAlignedScaledLarge_i, psi2Cx23CI95AlignedScaledLarge_i, tStartAlignedScaledLarge_i, tEndAlignedScaledLarge_i,...
            psi2Cx23MeanLarge_interictal, psi2Cx23CI95Large_interictal] = frAlign(interictalLargeInterp, psiCx23_t, tInterpFinal);
        [psi2Cx23iMeanAligned_i, psi2Cx23iCI95Aligned_i, ~, ~,...
            psi2Cx23iMeanAlignedScaled_i, psi2Cx23iCI95AlignedScaled_i, ~, ~,...
            psi2Cx23iMean_interictal, psi2Cx23iCI95_interictal] = frAlign(interictalInterp, psiCx23i_t, tInterpFinal);
        [psi2Cx23iMeanAlignedLarge_i, psi2Cx23iCI95AlignedLarge_i, ~, ~,...
            psi2Cx23iMeanAlignedScaledLarge_i, psi2Cx23iCI95AlignedScaledLarge_i, ~, ~,...
            psi2Cx23iMeanLarge_interictal, psi2Cx23iCI95Large_interictal] = frAlign(interictalLargeInterp, psiCx23i_t, tInterpFinal);
        [psi2Cx4MeanAligned_i, psi2Cx4CI95Aligned_i, ~, ~,...
            psi2Cx4MeanAlignedScaled_i, psi2Cx4CI95AlignedScaled_i, ~, ~,...
            psi2Cx4Mean_interictal, psi2Cx4CI95_interictal] = frAlign(interictalInterp, psiCx4_t, tInterpFinal);
        [psi2Cx4MeanAlignedLarge_i, psi2Cx4CI95AlignedLarge_i, ~, ~,...
            psi2Cx4MeanAlignedScaledLarge_i, psi2Cx4CI95AlignedScaledLarge_i, ~, ~,...
            psi2Cx4MeanLarge_interictal, psi2Cx4CI95Large_interictal] = frAlign(interictalLargeInterp, psiCx4_t, tInterpFinal);
        [psi2Cx4iMeanAligned_i, psi2Cx4iCI95Aligned_i, ~, ~,...
            psi2Cx4iMeanAlignedScaled_i, psi2Cx4iCI95AlignedScaled_i, ~, ~,...
            psi2Cx4iMean_interictal, psi2Cx4iCI95_interictal] = frAlign(interictalInterp, psiCx4i_t, tInterpFinal);
        [psi2Cx4iMeanAlignedLarge_i, psi2Cx4iCI95AlignedLarge_i, ~, ~,...
            psi2Cx4iMeanAlignedScaledLarge_i, psi2Cx4iCI95AlignedScaledLarge_i, ~, ~,...
            psi2Cx4iMeanLarge_interictal, psi2Cx4iCI95Large_interictal] = frAlign(interictalLargeInterp, psiCx4i_t, tInterpFinal);
        [psi2Cx5MeanAligned_i, psi2Cx5CI95Aligned_i, ~, ~,...
            psi2Cx5MeanAlignedScaled_i, psi2Cx5CI95AlignedScaled_i, ~, ~,...
            psi2Cx5Mean_interictal, psi2Cx5CI95_interictal] = frAlign(interictalInterp, psiCx5_t, tInterpFinal);
        [psi2Cx5MeanAlignedLarge_i, psi2Cx5CI95AlignedLarge_i, ~, ~,...
            psi2Cx5MeanAlignedScaledLarge_i, psi2Cx5CI95AlignedScaledLarge_i, ~, ~,...
            psi2Cx5MeanLarge_interictal, psi2Cx5CI95Large_interictal] = frAlign(interictalLargeInterp, psiCx5_t, tInterpFinal);
        [psi2Cx5iMeanAligned_i, psi2Cx5iCI95Aligned_i, ~, ~,...
            psi2Cx5iMeanAlignedScaled_i, psi2Cx5iCI95AlignedScaled_i, ~, ~,...
            psi2Cx5iMean_interictal, psi2Cx5iCI95_interictal] = frAlign(interictalInterp, psiCx5i_t, tInterpFinal);
        [psi2Cx5iMeanAlignedLarge_i, psi2Cx5iCI95AlignedLarge_i, ~, ~,...
            psi2Cx5iMeanAlignedScaledLarge_i, psi2Cx5iCI95AlignedScaledLarge_i, ~, ~,...
            psi2Cx5iMeanLarge_interictal, psi2Cx5iCI95Large_interictal] = frAlign(interictalLargeInterp, psiCx5i_t, tInterpFinal);
        [psi2Cx6MeanAligned_i, psi2Cx6CI95Aligned_i, ~, ~,...
            psi2Cx6MeanAlignedScaled_i, psi2Cx6CI95AlignedScaled_i, ~, ~,...
            psi2Cx6Mean_interictal, psi2Cx6CI95_interictal] = frAlign(interictalInterp, psiCx6_t, tInterpFinal);
        [psi2Cx6MeanAlignedLarge_i, psi2Cx6CI95AlignedLarge_i, ~, ~,...
            psi2Cx6MeanAlignedScaledLarge_i, psi2Cx6CI95AlignedScaledLarge_i, ~, ~,...
            psi2Cx6MeanLarge_interictal, psi2Cx6CI95Large_interictal] = frAlign(interictalLargeInterp, psiCx6_t, tInterpFinal);
        [psi2Cx6iMeanAligned_i, psi2Cx6iCI95Aligned_i, ~, ~,...
            psi2Cx6iMeanAlignedScaled_i, psi2Cx6iCI95AlignedScaled_i, ~, ~,...
            psi2Cx6iMean_interictal, psi2Cx6iCI95_interictal] = frAlign(interictalInterp, psiCx6i_t, tInterpFinal);
        [psi2Cx6iMeanAlignedLarge_i, psi2Cx6iCI95AlignedLarge_i, ~, ~,...
            psi2Cx6iMeanAlignedScaledLarge_i, psi2Cx6iCI95AlignedScaledLarge_i, ~, ~,...
            psi2Cx6iMeanLarge_interictal, psi2Cx6iCI95Large_interictal] = frAlign(interictalLargeInterp, psiCx6i_t, tInterpFinal);
        [psi2NRTMeanAligned_i, psi2NRTCI95Aligned_i, ~, ~,...
            psi2NRTMeanAlignedScaled_i, psi2NRTCI95AlignedScaled_i, ~, ~,...
            psi2NRTMean_interictal, psi2NRTCI95_interictal] = frAlign(interictalInterp, psiNRT_t, tInterpFinal);
        [psi2NRTMeanAlignedLarge_i, psi2NRTCI95AlignedLarge_i, ~, ~,...
            psi2NRTMeanAlignedScaledLarge_i, psi2NRTCI95AlignedScaledLarge_i, ~, ~,...
            psi2NRTMeanLarge_interictal, psi2NRTCI95Large_interictal] = frAlign(interictalLargeInterp, psiNRT_t, tInterpFinal);
        [psi2NRT2MeanAligned_i, psi2NRT2CI95Aligned_i, ~, ~,...
            psi2NRT2MeanAlignedScaled_i, psi2NRT2CI95AlignedScaled_i, ~, ~,...
            psi2NRT2Mean_interictal, psi2NRT2CI95_interictal] = frAlign(interictalInterp, psiNRT2_t, tInterpFinal);
        [psi2NRT2MeanAlignedLarge_i, psi2NRT2CI95AlignedLarge_i, ~, ~,...
            psi2NRT2MeanAlignedScaledLarge_i, psi2NRT2CI95AlignedScaledLarge_i, ~, ~,...
            psi2NRT2MeanLarge_interictal, psi2NRT2CI95Large_interictal] = frAlign(interictalLargeInterp, psiNRT2_t, tInterpFinal);
        [psi2TCMeanAligned_i, psi2TCCI95Aligned_i, ~, ~,...
            psi2TCMeanAlignedScaled_i, psi2TCCI95AlignedScaled_i, ~, ~,...
            psi2TCMean_interictal, psi2TCCI95_interictal] = frAlign(interictalInterp, psiTC_t, tInterpFinal);
        [psi2TCMeanAlignedLarge_i, psi2TCCI95AlignedLarge_i, ~, ~,...
            psi2TCMeanAlignedScaledLarge_i, psi2TCCI95AlignedScaledLarge_i, ~, ~,...
            psi2TCMeanLarge_interictal, psi2TCCI95Large_interictal] = frAlign(interictalLargeInterp, psiTC_t, tInterpFinal);
        [psi2TC2MeanAligned_i, psi2TC2CI95Aligned_i, ~, ~,...
            psi2TC2MeanAlignedScaled_i, psi2TC2CI95AlignedScaled_i, ~, ~,...
            psi2TC2Mean_interictal, psi2TC2CI95_interictal] = frAlign(interictalInterp, psiTC2_t, tInterpFinal);
        [psi2TC2MeanAlignedLarge_i, psi2TC2CI95AlignedLarge_i, ~, ~,...
            psi2TC2MeanAlignedScaledLarge_i, psi2TC2CI95AlignedScaledLarge_i, ~, ~,...
            psi2TC2MeanLarge_interictal, psi2TC2CI95Large_interictal] = frAlign(interictalLargeInterp, psiTC2_t, tInterpFinal);
        
        psi2MeanAlignedScaled = [psi2Cx23MeanAlignedScaled; psi2Cx23iMeanAlignedScaled; psi2Cx4MeanAlignedScaled; psi2Cx4iMeanAlignedScaled;...
            psi2Cx5MeanAlignedScaled; psi2Cx5iMeanAlignedScaled; psi2Cx6MeanAlignedScaled; psi2Cx6iMeanAlignedScaled;
            psi2NRTMeanAlignedScaled; psi2NRT2MeanAlignedScaled; psi2TCMeanAlignedScaled; psi2TC2MeanAlignedScaled];
        psi2CI95AlignedScaled = [psi2Cx23CI95AlignedScaled; psi2Cx23iCI95AlignedScaled; psi2Cx4CI95AlignedScaled; psi2Cx4iCI95AlignedScaled;...
            psi2Cx5CI95AlignedScaled; psi2Cx5iCI95AlignedScaled; psi2Cx6CI95AlignedScaled; psi2Cx6iCI95AlignedScaled;
            psi2NRTCI95AlignedScaled; psi2NRT2CI95AlignedScaled; psi2TCCI95AlignedScaled; psi2TC2CI95AlignedScaled];
        psi2MeanAlignedScaled_i = [psi2Cx23MeanAlignedScaled_i; psi2Cx23iMeanAlignedScaled_i; psi2Cx4MeanAlignedScaled_i; psi2Cx4iMeanAlignedScaled_i;...
            psi2Cx5MeanAlignedScaled_i; psi2Cx5iMeanAlignedScaled_i; psi2Cx6MeanAlignedScaled_i; psi2Cx6iMeanAlignedScaled_i;
            psi2NRTMeanAlignedScaled_i; psi2NRT2MeanAlignedScaled_i; psi2TCMeanAlignedScaled_i; psi2TC2MeanAlignedScaled_i];
        psi2CI95AlignedScaled_i = [psi2Cx23CI95AlignedScaled_i; psi2Cx23iCI95AlignedScaled_i; psi2Cx4CI95AlignedScaled_i; psi2Cx4iCI95AlignedScaled_i;...
            psi2Cx5CI95AlignedScaled_i; psi2Cx5iCI95AlignedScaled_i; psi2Cx6CI95AlignedScaled_i; psi2Cx6iCI95AlignedScaled_i;
            psi2NRTCI95AlignedScaled_i; psi2NRT2CI95AlignedScaled_i; psi2TCCI95AlignedScaled_i; psi2TC2CI95AlignedScaled_i];
    end
    
    if spiking
        disp('Processing spiking PSIs')
        [psi2RasterCx23MeanAligned, psi2RasterCx23CI95Aligned, tStartAligned, tEndAligned,...
            psi2RasterCx23MeanAlignedScaled, psi2RasterCx23CI95AlignedScaled, tStartAlignedScaled, tEndAlignedScaled,...
            psi2RasterCx23Mean_SWDs, psi2RasterCx23CI95_SWDs] = frAlign(SWDsInterp, psiRasterCx23_t, tInterpFinal);
        [psi2RasterCx23MeanAlignedLarge, psi2RasterCx23CI95AlignedLarge, tStartAlignedLarge, tEndAlignedLarge,...
            psi2RasterCx23MeanAlignedScaledLarge, psi2RasterCx23CI95AlignedScaledLarge, tStartAlignedScaledLarge, tEndAlignedScaledLarge,...
            psi2RasterCx23MeanLarge_SWDs, psi2RasterCx23CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterCx23_t, tInterpFinal);
        [psi2RasterCx23iMeanAligned, psi2RasterCx23iCI95Aligned, ~, ~,...
            psi2RasterCx23iMeanAlignedScaled, psi2RasterCx23iCI95AlignedScaled, ~, ~,...
            psi2RasterCx23iMean_SWDs, psi2RasterCx23iCI95_SWDs] = frAlign(SWDsInterp, psiRasterCx23i_t, tInterpFinal);
        [psi2RasterCx23iMeanAlignedLarge, psi2RasterCx23iCI95AlignedLarge, ~, ~,...
            psi2RasterCx23iMeanAlignedScaledLarge, psi2RasterCx23iCI95AlignedScaledLarge, ~, ~,...
            psi2RasterCx23iMeanLarge_SWDs, psi2RasterCx23iCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterCx23i_t, tInterpFinal);
        [psi2RasterCx4MeanAligned, psi2RasterCx4CI95Aligned, ~, ~,...
            psi2RasterCx4MeanAlignedScaled, psi2RasterCx4CI95AlignedScaled, ~, ~,...
            psi2RasterCx4Mean_SWDs, psi2RasterCx4CI95_SWDs] = frAlign(SWDsInterp, psiRasterCx4_t, tInterpFinal);
        [psi2RasterCx4MeanAlignedLarge, psi2RasterCx4CI95AlignedLarge, ~, ~,...
            psi2RasterCx4MeanAlignedScaledLarge, psi2RasterCx4CI95AlignedScaledLarge, ~, ~,...
            psi2RasterCx4MeanLarge_SWDs, psi2RasterCx4CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterCx4_t, tInterpFinal);
        [psi2RasterCx4iMeanAligned, psi2RasterCx4iCI95Aligned, ~, ~,...
            psi2RasterCx4iMeanAlignedScaled, psi2RasterCx4iCI95AlignedScaled, ~, ~,...
            psi2RasterCx4iMean_SWDs, psi2RasterCx4iCI95_SWDs] = frAlign(SWDsInterp, psiRasterCx4i_t, tInterpFinal);
        [psi2RasterCx4iMeanAlignedLarge, psi2RasterCx4iCI95AlignedLarge, ~, ~,...
            psi2RasterCx4iMeanAlignedScaledLarge, psi2RasterCx4iCI95AlignedScaledLarge, ~, ~,...
            psi2RasterCx4iMeanLarge_SWDs, psi2RasterCx4iCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterCx4i_t, tInterpFinal);
        [psi2RasterCx5MeanAligned, psi2RasterCx5CI95Aligned, ~, ~,...
            psi2RasterCx5MeanAlignedScaled, psi2RasterCx5CI95AlignedScaled, ~, ~,...
            psi2RasterCx5Mean_SWDs, psi2RasterCx5CI95_SWDs] = frAlign(SWDsInterp, psiRasterCx5_t, tInterpFinal);
        [psi2RasterCx5MeanAlignedLarge, psi2RasterCx5CI95AlignedLarge, ~, ~,...
            psi2RasterCx5MeanAlignedScaledLarge, psi2RasterCx5CI95AlignedScaledLarge, ~, ~,...
            psi2RasterCx5MeanLarge_SWDs, psi2RasterCx5CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterCx5_t, tInterpFinal);
        [psi2RasterCx5iMeanAligned, psi2RasterCx5iCI95Aligned, ~, ~,...
            psi2RasterCx5iMeanAlignedScaled, psi2RasterCx5iCI95AlignedScaled, ~, ~,...
            psi2RasterCx5iMean_SWDs, psi2RasterCx5iCI95_SWDs] = frAlign(SWDsInterp, psiRasterCx5i_t, tInterpFinal);
        [psi2RasterCx5iMeanAlignedLarge, psi2RasterCx5iCI95AlignedLarge, ~, ~,...
            psi2RasterCx5iMeanAlignedScaledLarge, psi2RasterCx5iCI95AlignedScaledLarge, ~, ~,...
            psi2RasterCx5iMeanLarge_SWDs, psi2RasterCx5iCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterCx5i_t, tInterpFinal);
        [psi2RasterCx6MeanAligned, psi2RasterCx6CI95Aligned, ~, ~,...
            psi2RasterCx6MeanAlignedScaled, psi2RasterCx6CI95AlignedScaled, ~, ~,...
            psi2RasterCx6Mean_SWDs, psi2RasterCx6CI95_SWDs] = frAlign(SWDsInterp, psiRasterCx6_t, tInterpFinal);
        [psi2RasterCx6MeanAlignedLarge, psi2RasterCx6CI95AlignedLarge, ~, ~,...
            psi2RasterCx6MeanAlignedScaledLarge, psi2RasterCx6CI95AlignedScaledLarge, ~, ~,...
            psi2RasterCx6MeanLarge_SWDs, psi2RasterCx6CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterCx6_t, tInterpFinal);
        [psi2RasterCx6iMeanAligned, psi2RasterCx6iCI95Aligned, ~, ~,...
            psi2RasterCx6iMeanAlignedScaled, psi2RasterCx6iCI95AlignedScaled, ~, ~,...
            psi2RasterCx6iMean_SWDs, psi2RasterCx6iCI95_SWDs] = frAlign(SWDsInterp, psiRasterCx6i_t, tInterpFinal);
        [psi2RasterCx6iMeanAlignedLarge, psi2RasterCx6iCI95AlignedLarge, ~, ~,...
            psi2RasterCx6iMeanAlignedScaledLarge, psi2RasterCx6iCI95AlignedScaledLarge, ~, ~,...
            psi2RasterCx6iMeanLarge_SWDs, psi2RasterCx6iCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterCx6i_t, tInterpFinal);
        [psi2RasterNRTMeanAligned, psi2RasterNRTCI95Aligned, ~, ~,...
            psi2RasterNRTMeanAlignedScaled, psi2RasterNRTCI95AlignedScaled, ~, ~,...
            psi2RasterNRTMean_SWDs, psi2RasterNRTCI95_SWDs] = frAlign(SWDsInterp, psiRasterNRT_t, tInterpFinal);
        [psi2RasterNRTMeanAlignedLarge, psi2RasterNRTCI95AlignedLarge, ~, ~,...
            psi2RasterNRTMeanAlignedScaledLarge, psi2RasterNRTCI95AlignedScaledLarge, ~, ~,...
            psi2RasterNRTMeanLarge_SWDs, psi2RasterNRTCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterNRT_t, tInterpFinal);
        [psi2RasterNRT2MeanAligned, psi2RasterNRT2CI95Aligned, ~, ~,...
            psi2RasterNRT2MeanAlignedScaled, psi2RasterNRT2CI95AlignedScaled, ~, ~,...
            psi2RasterNRT2Mean_SWDs, psi2RasterNRT2CI95_SWDs] = frAlign(SWDsInterp, psiRasterNRT2_t, tInterpFinal);
        [psi2RasterNRT2MeanAlignedLarge, psi2RasterNRT2CI95AlignedLarge, ~, ~,...
            psi2RasterNRT2MeanAlignedScaledLarge, psi2RasterNRT2CI95AlignedScaledLarge, ~, ~,...
            psi2RasterNRT2MeanLarge_SWDs, psi2RasterNRT2CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterNRT2_t, tInterpFinal);
        [psi2RasterTCMeanAligned, psi2RasterTCCI95Aligned, ~, ~,...
            psi2RasterTCMeanAlignedScaled, psi2RasterTCCI95AlignedScaled, ~, ~,...
            psi2RasterTCMean_SWDs, psi2RasterTCCI95_SWDs] = frAlign(SWDsInterp, psiRasterTC_t, tInterpFinal);
        [psi2RasterTCMeanAlignedLarge, psi2RasterTCCI95AlignedLarge, ~, ~,...
            psi2RasterTCMeanAlignedScaledLarge, psi2RasterTCCI95AlignedScaledLarge, ~, ~,...
            psi2RasterTCMeanLarge_SWDs, psi2RasterTCCI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterTC_t, tInterpFinal);
        [psi2RasterTC2MeanAligned, psi2RasterTC2CI95Aligned, ~, ~,...
            psi2RasterTC2MeanAlignedScaled, psi2RasterTC2CI95AlignedScaled, ~, ~,...
            psi2RasterTC2Mean_SWDs, psi2RasterTC2CI95_SWDs] = frAlign(SWDsInterp, psiRasterTC2_t, tInterpFinal);
        [psi2RasterTC2MeanAlignedLarge, psi2RasterTC2CI95AlignedLarge, ~, ~,...
            psi2RasterTC2MeanAlignedScaledLarge, psi2RasterTC2CI95AlignedScaledLarge, ~, ~,...
            psi2RasterTC2MeanLarge_SWDs, psi2RasterTC2CI95Large_SWDs] = frAlign(SWDsLargeInterp, psiRasterTC2_t, tInterpFinal);
        
        [psi2RasterCx23MeanAligned_i, psi2RasterCx23CI95Aligned_i, tStartAligned_i, tEndAligned_i,...
            psi2RasterCx23MeanAlignedScaled_i, psi2RasterCx23CI95AlignedScaled_i, tStartAlignedScaled_i, tEndAlignedScaled_i,...
            psi2RasterCx23Mean_interictal, psi2RasterCx23CI95_interictal] = frAlign(interictalInterp, psiRasterCx23_t, tInterpFinal);
        [psi2RasterCx23MeanAlignedLarge_i, psi2RasterCx23CI95AlignedLarge_i, tStartAlignedLarge_i, tEndAlignedLarge_i,...
            psi2RasterCx23MeanAlignedScaledLarge_i, psi2RasterCx23CI95AlignedScaledLarge_i, tStartAlignedScaledLarge_i, tEndAlignedScaledLarge_i,...
            psi2RasterCx23MeanLarge_interictal, psi2RasterCx23CI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterCx23_t, tInterpFinal);
        [psi2RasterCx23iMeanAligned_i, psi2RasterCx23iCI95Aligned_i, ~, ~,...
            psi2RasterCx23iMeanAlignedScaled_i, psi2RasterCx23iCI95AlignedScaled_i, ~, ~,...
            psi2RasterCx23iMean_interictal, psi2RasterCx23iCI95_interictal] = frAlign(interictalInterp, psiRasterCx23i_t, tInterpFinal);
        [psi2RasterCx23iMeanAlignedLarge_i, psi2RasterCx23iCI95AlignedLarge_i, ~, ~,...
            psi2RasterCx23iMeanAlignedScaledLarge_i, psi2RasterCx23iCI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterCx23iMeanLarge_interictal, psi2RasterCx23iCI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterCx23i_t, tInterpFinal);
        [psi2RasterCx4MeanAligned_i, psi2RasterCx4CI95Aligned_i, ~, ~,...
            psi2RasterCx4MeanAlignedScaled_i, psi2RasterCx4CI95AlignedScaled_i, ~, ~,...
            psi2RasterCx4Mean_interictal, psi2RasterCx4CI95_interictal] = frAlign(interictalInterp, psiRasterCx4_t, tInterpFinal);
        [psi2RasterCx4MeanAlignedLarge_i, psi2RasterCx4CI95AlignedLarge_i, ~, ~,...
            psi2RasterCx4MeanAlignedScaledLarge_i, psi2RasterCx4CI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterCx4MeanLarge_interictal, psi2RasterCx4CI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterCx4_t, tInterpFinal);
        [psi2RasterCx4iMeanAligned_i, psi2RasterCx4iCI95Aligned_i, ~, ~,...
            psi2RasterCx4iMeanAlignedScaled_i, psi2RasterCx4iCI95AlignedScaled_i, ~, ~,...
            psi2RasterCx4iMean_interictal, psi2RasterCx4iCI95_interictal] = frAlign(interictalInterp, psiRasterCx4i_t, tInterpFinal);
        [psi2RasterCx4iMeanAlignedLarge_i, psi2RasterCx4iCI95AlignedLarge_i, ~, ~,...
            psi2RasterCx4iMeanAlignedScaledLarge_i, psi2RasterCx4iCI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterCx4iMeanLarge_interictal, psi2RasterCx4iCI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterCx4i_t, tInterpFinal);
        [psi2RasterCx5MeanAligned_i, psi2RasterCx5CI95Aligned_i, ~, ~,...
            psi2RasterCx5MeanAlignedScaled_i, psi2RasterCx5CI95AlignedScaled_i, ~, ~,...
            psi2RasterCx5Mean_interictal, psi2RasterCx5CI95_interictal] = frAlign(interictalInterp, psiRasterCx5_t, tInterpFinal);
        [psi2RasterCx5MeanAlignedLarge_i, psi2RasterCx5CI95AlignedLarge_i, ~, ~,...
            psi2RasterCx5MeanAlignedScaledLarge_i, psi2RasterCx5CI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterCx5MeanLarge_interictal, psi2RasterCx5CI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterCx5_t, tInterpFinal);
        [psi2RasterCx5iMeanAligned_i, psi2RasterCx5iCI95Aligned_i, ~, ~,...
            psi2RasterCx5iMeanAlignedScaled_i, psi2RasterCx5iCI95AlignedScaled_i, ~, ~,...
            psi2RasterCx5iMean_interictal, psi2RasterCx5iCI95_interictal] = frAlign(interictalInterp, psiRasterCx5i_t, tInterpFinal);
        [psi2RasterCx5iMeanAlignedLarge_i, psi2RasterCx5iCI95AlignedLarge_i, ~, ~,...
            psi2RasterCx5iMeanAlignedScaledLarge_i, psi2RasterCx5iCI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterCx5iMeanLarge_interictal, psi2RasterCx5iCI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterCx5i_t, tInterpFinal);
        [psi2RasterCx6MeanAligned_i, psi2RasterCx6CI95Aligned_i, ~, ~,...
            psi2RasterCx6MeanAlignedScaled_i, psi2RasterCx6CI95AlignedScaled_i, ~, ~,...
            psi2RasterCx6Mean_interictal, psi2RasterCx6CI95_interictal] = frAlign(interictalInterp, psiRasterCx6_t, tInterpFinal);
        [psi2RasterCx6MeanAlignedLarge_i, psi2RasterCx6CI95AlignedLarge_i, ~, ~,...
            psi2RasterCx6MeanAlignedScaledLarge_i, psi2RasterCx6CI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterCx6MeanLarge_interictal, psi2RasterCx6CI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterCx6_t, tInterpFinal);
        [psi2RasterCx6iMeanAligned_i, psi2RasterCx6iCI95Aligned_i, ~, ~,...
            psi2RasterCx6iMeanAlignedScaled_i, psi2RasterCx6iCI95AlignedScaled_i, ~, ~,...
            psi2RasterCx6iMean_interictal, psi2RasterCx6iCI95_interictal] = frAlign(interictalInterp, psiRasterCx6i_t, tInterpFinal);
        [psi2RasterCx6iMeanAlignedLarge_i, psi2RasterCx6iCI95AlignedLarge_i, ~, ~,...
            psi2RasterCx6iMeanAlignedScaledLarge_i, psi2RasterCx6iCI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterCx6iMeanLarge_interictal, psi2RasterCx6iCI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterCx6i_t, tInterpFinal);
        [psi2RasterNRTMeanAligned_i, psi2RasterNRTCI95Aligned_i, ~, ~,...
            psi2RasterNRTMeanAlignedScaled_i, psi2RasterNRTCI95AlignedScaled_i, ~, ~,...
            psi2RasterNRTMean_interictal, psi2RasterNRTCI95_interictal] = frAlign(interictalInterp, psiRasterNRT_t, tInterpFinal);
        [psi2RasterNRTMeanAlignedLarge_i, psi2RasterNRTCI95AlignedLarge_i, ~, ~,...
            psi2RasterNRTMeanAlignedScaledLarge_i, psi2RasterNRTCI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterNRTMeanLarge_interictal, psi2RasterNRTCI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterNRT_t, tInterpFinal);
        [psi2RasterNRT2MeanAligned_i, psi2RasterNRT2CI95Aligned_i, ~, ~,...
            psi2RasterNRT2MeanAlignedScaled_i, psi2RasterNRT2CI95AlignedScaled_i, ~, ~,...
            psi2RasterNRT2Mean_interictal, psi2RasterNRT2CI95_interictal] = frAlign(interictalInterp, psiRasterNRT2_t, tInterpFinal);
        [psi2RasterNRT2MeanAlignedLarge_i, psi2RasterNRT2CI95AlignedLarge_i, ~, ~,...
            psi2RasterNRT2MeanAlignedScaledLarge_i, psi2RasterNRT2CI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterNRT2MeanLarge_interictal, psi2RasterNRT2CI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterNRT2_t, tInterpFinal);
        [psi2RasterTCMeanAligned_i, psi2RasterTCCI95Aligned_i, ~, ~,...
            psi2RasterTCMeanAlignedScaled_i, psi2RasterTCCI95AlignedScaled_i, ~, ~,...
            psi2RasterTCMean_interictal, psi2RasterTCCI95_interictal] = frAlign(interictalInterp, psiRasterTC_t, tInterpFinal);
        [psi2RasterTCMeanAlignedLarge_i, psi2RasterTCCI95AlignedLarge_i, ~, ~,...
            psi2RasterTCMeanAlignedScaledLarge_i, psi2RasterTCCI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterTCMeanLarge_interictal, psi2RasterTCCI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterTC_t, tInterpFinal);
        [psi2RasterTC2MeanAligned_i, psi2RasterTC2CI95Aligned_i, ~, ~,...
            psi2RasterTC2MeanAlignedScaled_i, psi2RasterTC2CI95AlignedScaled_i, ~, ~,...
            psi2RasterTC2Mean_interictal, psi2RasterTC2CI95_interictal] = frAlign(interictalInterp, psiRasterTC2_t, tInterpFinal);
        [psi2RasterTC2MeanAlignedLarge_i, psi2RasterTC2CI95AlignedLarge_i, ~, ~,...
            psi2RasterTC2MeanAlignedScaledLarge_i, psi2RasterTC2CI95AlignedScaledLarge_i, ~, ~,...
            psi2RasterTC2MeanLarge_interictal, psi2RasterTC2CI95Large_interictal] = frAlign(interictalLargeInterp, psiRasterTC2_t, tInterpFinal);
        
        psi2RasterMeanAlignedScaled = [psi2RasterCx23MeanAlignedScaled; psi2RasterCx23iMeanAlignedScaled; psi2RasterCx4MeanAlignedScaled;...
            psi2RasterCx4iMeanAlignedScaled; psi2RasterCx5MeanAlignedScaled; psi2RasterCx5iMeanAlignedScaled; psi2RasterCx6MeanAlignedScaled;...
            psi2RasterCx6iMeanAlignedScaled; psi2RasterNRTMeanAlignedScaled; psi2RasterNRT2MeanAlignedScaled; psi2RasterTCMeanAlignedScaled;...
            psi2RasterTC2MeanAlignedScaled];
        psi2RasterCI95AlignedScaled = [psi2RasterCx23CI95AlignedScaled; psi2RasterCx23iCI95AlignedScaled; psi2RasterCx4CI95AlignedScaled;...
            psi2RasterCx4iCI95AlignedScaled; psi2RasterCx5CI95AlignedScaled; psi2RasterCx5iCI95AlignedScaled; psi2RasterCx6CI95AlignedScaled;...
            psi2RasterCx6iCI95AlignedScaled; psi2RasterNRTCI95AlignedScaled; psi2RasterNRT2CI95AlignedScaled; psi2RasterTCCI95AlignedScaled;...
            psi2RasterTC2CI95AlignedScaled];
        psi2RasterMeanAlignedScaled_i = [psi2RasterCx23MeanAlignedScaled_i; psi2RasterCx23iMeanAlignedScaled_i; psi2RasterCx4MeanAlignedScaled_i;...
            psi2RasterCx4iMeanAlignedScaled_i; psi2RasterCx5MeanAlignedScaled_i; psi2RasterCx5iMeanAlignedScaled_i; psi2RasterCx6MeanAlignedScaled_i;...
            psi2RasterCx6iMeanAlignedScaled_i; psi2RasterNRTMeanAlignedScaled_i; psi2RasterNRT2MeanAlignedScaled_i; psi2RasterTCMeanAlignedScaled_i;...
            psi2RasterTC2MeanAlignedScaled_i];
        psi2RasterCI95AlignedScaled_i = [psi2RasterCx23CI95AlignedScaled_i; psi2RasterCx23iCI95AlignedScaled_i; psi2RasterCx4CI95AlignedScaled_i;...
            psi2RasterCx4iCI95AlignedScaled_i; psi2RasterCx5CI95AlignedScaled_i; psi2RasterCx5iCI95AlignedScaled_i; psi2RasterCx6CI95AlignedScaled_i;...
            psi2RasterCx6iCI95AlignedScaled_i; psi2RasterNRTCI95AlignedScaled_i; psi2RasterNRT2CI95AlignedScaled_i; psi2RasterTCCI95AlignedScaled_i;...
            psi2RasterTC2CI95AlignedScaled_i];
    end
end


%% Save data
if fullRun
    disp('Saving data')
    if voltage && ~spiking
        save('psiData2.mat', 'dt','t','dtInterpInit','dtInterpFinal','tInterpInit','tInterpFinal',...
            'psiCx23','psiCx23i','psiCx4','psiCx4i','psiCx5','psiCx5i',...
            'psiCx6','psiCx6i','psiNRT','psiNRT2','psiTC','psiTC2',...
            'psi2Cx23mean','psi2Cx23CI95','psi2Cx23imean','psi2Cx23iCI95',...
            'psi2Cx4mean','psi2Cx4CI95','psi2Cx4imean','psi2Cx4iCI95',...
            'psi2Cx5mean','psi2Cx5CI95','psi2Cx5imean','psi2Cx5iCI95',...
            'psi2Cx6mean','psi2Cx6CI95','psi2Cx6imean','psi2Cx6iCI95',...
            'psi2NRTmean','psi2NRTCI95','psi2NRT2mean','psi2NRT2CI95',...
            'psi2TCmean','psi2TCCI95','psi2TC2mean','psi2TC2CI95',...
            'psi2Cx23MeanAligned','psi2Cx23CI95Aligned','psi2Cx23iMeanAligned','psi2Cx23iCI95Aligned',...
            'psi2Cx4MeanAligned','psi2Cx4CI95Aligned','psi2Cx4iMeanAligned','psi2Cx4iCI95Aligned',...
            'psi2Cx5MeanAligned','psi2Cx5CI95Aligned','psi2Cx5iMeanAligned','psi2Cx5iCI95Aligned',...
            'psi2Cx6MeanAligned','psi2Cx6CI95Aligned','psi2Cx6iMeanAligned','psi2Cx6iCI95Aligned',...
            'psi2NRTMeanAligned','psi2NRTCI95Aligned','psi2NRT2MeanAligned','psi2NRT2CI95Aligned',...
            'psi2TCMeanAligned','psi2TCCI95Aligned','psi2TC2MeanAligned','psi2TC2CI95Aligned',...
            'psi2Cx23MeanAlignedScaled','psi2Cx23CI95AlignedScaled','psi2Cx23iMeanAlignedScaled','psi2Cx23iCI95AlignedScaled',...
            'psi2Cx4MeanAlignedScaled','psi2Cx4CI95AlignedScaled','psi2Cx4iMeanAlignedScaled','psi2Cx4iCI95AlignedScaled',...
            'psi2Cx5MeanAlignedScaled','psi2Cx5CI95AlignedScaled','psi2Cx5iMeanAlignedScaled','psi2Cx5iCI95AlignedScaled',...
            'psi2Cx6MeanAlignedScaled','psi2Cx6CI95AlignedScaled','psi2Cx6iMeanAlignedScaled','psi2Cx6iCI95AlignedScaled',...
            'psi2NRTMeanAlignedScaled','psi2NRTCI95AlignedScaled','psi2NRT2MeanAlignedScaled','psi2NRT2CI95AlignedScaled',...
            'psi2TCMeanAlignedScaled','psi2TCCI95AlignedScaled','psi2TC2MeanAlignedScaled','psi2TC2CI95AlignedScaled',...
            'psi2Cx23MeanAlignedLarge','psi2Cx23CI95AlignedLarge','psi2Cx23iMeanAlignedLarge','psi2Cx23iCI95AlignedLarge',...
            'psi2Cx4MeanAlignedLarge','psi2Cx4CI95AlignedLarge','psi2Cx4iMeanAlignedLarge','psi2Cx4iCI95AlignedLarge',...
            'psi2Cx5MeanAlignedLarge','psi2Cx5CI95AlignedLarge','psi2Cx5iMeanAlignedLarge','psi2Cx5iCI95AlignedLarge',...
            'psi2Cx6MeanAlignedLarge','psi2Cx6CI95AlignedLarge','psi2Cx6iMeanAlignedLarge','psi2Cx6iCI95AlignedLarge',...
            'psi2NRTMeanAlignedLarge','psi2NRTCI95AlignedLarge','psi2NRT2MeanAlignedLarge','psi2NRT2CI95AlignedLarge',...
            'psi2TCMeanAlignedLarge','psi2TCCI95AlignedLarge','psi2TC2MeanAlignedLarge','psi2TC2CI95AlignedLarge',...
            'psi2Cx23MeanAlignedScaledLarge','psi2Cx23CI95AlignedScaledLarge','psi2Cx23iMeanAlignedScaledLarge','psi2Cx23iCI95AlignedScaledLarge',...
            'psi2Cx4MeanAlignedScaledLarge','psi2Cx4CI95AlignedScaledLarge','psi2Cx4iMeanAlignedScaledLarge','psi2Cx4iCI95AlignedScaledLarge',...
            'psi2Cx5MeanAlignedScaledLarge','psi2Cx5CI95AlignedScaledLarge','psi2Cx5iMeanAlignedScaledLarge','psi2Cx5iCI95AlignedScaledLarge',...
            'psi2Cx6MeanAlignedScaledLarge','psi2Cx6CI95AlignedScaledLarge','psi2Cx6iMeanAlignedScaledLarge','psi2Cx6iCI95AlignedScaledLarge',...
            'psi2NRTMeanAlignedScaledLarge','psi2NRTCI95AlignedScaledLarge','psi2NRT2MeanAlignedScaledLarge','psi2NRT2CI95AlignedScaledLarge',...
            'psi2TCMeanAlignedScaledLarge','psi2TCCI95AlignedScaledLarge','psi2TC2MeanAlignedScaledLarge','psi2TC2CI95AlignedScaledLarge',...
            'tStartAligned','tEndAligned','tStartAlignedLarge','tEndAlignedLarge',...
            'tStartAlignedScaled','tEndAlignedScaled','tStartAlignedScaledLarge','tEndAlignedScaledLarge',...
            'psi2Cx23MeanAligned_i','psi2Cx23CI95Aligned_i','psi2Cx23iMeanAligned_i','psi2Cx23iCI95Aligned_i',...
            'psi2Cx4MeanAligned_i','psi2Cx4CI95Aligned_i','psi2Cx4iMeanAligned_i','psi2Cx4iCI95Aligned_i',...
            'psi2Cx5MeanAligned_i','psi2Cx5CI95Aligned_i','psi2Cx5iMeanAligned_i','psi2Cx5iCI95Aligned_i',...
            'psi2Cx6MeanAligned_i','psi2Cx6CI95Aligned_i','psi2Cx6iMeanAligned_i','psi2Cx6iCI95Aligned_i',...
            'psi2NRTMeanAligned_i','psi2NRTCI95Aligned_i','psi2NRT2MeanAligned_i','psi2NRT2CI95Aligned_i',...
            'psi2TCMeanAligned_i','psi2TCCI95Aligned_i','psi2TC2MeanAligned_i','psi2TC2CI95Aligned_i',...
            'psi2Cx23MeanAlignedScaled_i','psi2Cx23CI95AlignedScaled_i','psi2Cx23iMeanAlignedScaled_i','psi2Cx23iCI95AlignedScaled_i',...
            'psi2Cx4MeanAlignedScaled_i','psi2Cx4CI95AlignedScaled_i','psi2Cx4iMeanAlignedScaled_i','psi2Cx4iCI95AlignedScaled_i',...
            'psi2Cx5MeanAlignedScaled_i','psi2Cx5CI95AlignedScaled_i','psi2Cx5iMeanAlignedScaled_i','psi2Cx5iCI95AlignedScaled_i',...
            'psi2Cx6MeanAlignedScaled_i','psi2Cx6CI95AlignedScaled_i','psi2Cx6iMeanAlignedScaled_i','psi2Cx6iCI95AlignedScaled_i',...
            'psi2NRTMeanAlignedScaled_i','psi2NRTCI95AlignedScaled_i','psi2NRT2MeanAlignedScaled_i','psi2NRT2CI95AlignedScaled_i',...
            'psi2TCMeanAlignedScaled_i','psi2TCCI95AlignedScaled_i','psi2TC2MeanAlignedScaled_i','psi2TC2CI95AlignedScaled_i',...
            'psi2Cx23MeanAlignedLarge_i','psi2Cx23CI95AlignedLarge_i','psi2Cx23iMeanAlignedLarge_i','psi2Cx23iCI95AlignedLarge_i',...
            'psi2Cx4MeanAlignedLarge_i','psi2Cx4CI95AlignedLarge_i','psi2Cx4iMeanAlignedLarge_i','psi2Cx4iCI95AlignedLarge_i',...
            'psi2Cx5MeanAlignedLarge_i','psi2Cx5CI95AlignedLarge_i','psi2Cx5iMeanAlignedLarge_i','psi2Cx5iCI95AlignedLarge_i',...
            'psi2Cx6MeanAlignedLarge_i','psi2Cx6CI95AlignedLarge_i','psi2Cx6iMeanAlignedLarge_i','psi2Cx6iCI95AlignedLarge_i',...
            'psi2NRTMeanAlignedLarge_i','psi2NRTCI95AlignedLarge_i','psi2NRT2MeanAlignedLarge_i','psi2NRT2CI95AlignedLarge_i',...
            'psi2TCMeanAlignedLarge_i','psi2TCCI95AlignedLarge_i','psi2TC2MeanAlignedLarge_i','psi2TC2CI95AlignedLarge_i',...
            'psi2Cx23MeanAlignedScaledLarge_i','psi2Cx23CI95AlignedScaledLarge_i','psi2Cx23iMeanAlignedScaledLarge_i','psi2Cx23iCI95AlignedScaledLarge_i',...
            'psi2Cx4MeanAlignedScaledLarge_i','psi2Cx4CI95AlignedScaledLarge_i','psi2Cx4iMeanAlignedScaledLarge_i','psi2Cx4iCI95AlignedScaledLarge_i',...
            'psi2Cx5MeanAlignedScaledLarge_i','psi2Cx5CI95AlignedScaledLarge_i','psi2Cx5iMeanAlignedScaledLarge_i','psi2Cx5iCI95AlignedScaledLarge_i',...
            'psi2Cx6MeanAlignedScaledLarge_i','psi2Cx6CI95AlignedScaledLarge_i','psi2Cx6iMeanAlignedScaledLarge_i','psi2Cx6iCI95AlignedScaledLarge_i',...
            'psi2NRTMeanAlignedScaledLarge_i','psi2NRTCI95AlignedScaledLarge_i','psi2NRT2MeanAlignedScaledLarge_i','psi2NRT2CI95AlignedScaledLarge_i',...
            'psi2TCMeanAlignedScaledLarge_i','psi2TCCI95AlignedScaledLarge_i','psi2TC2MeanAlignedScaledLarge_i','psi2TC2CI95AlignedScaledLarge_i',...
            'psi2MeanAlignedScaled','psi2CI95AlignedScaled', 'psi2MeanAlignedScaled_i','psi2CI95AlignedScaled_i',...
            'tStartAligned_i','tEndAligned_i','tStartAlignedLarge_i','tEndAlignedLarge_i',...
            'tStartAlignedScaled_i','tEndAlignedScaled_i','tStartAlignedScaledLarge_i','tEndAlignedScaledLarge_i',...
            'iRange','nIN','nNRT','nPY','nTC','psiWindow');
    elseif ~voltage && spiking
        save('psiData2.mat', 'dt','t','dtInterpInit','dtInterpFinal','tInterpInit','tInterpFinal',...
            'psiRasterCx23','psiRasterCx23i','psiRasterCx4','psiRasterCx4i','psiRasterCx5','psiRasterCx5i',...
            'psiRasterCx6','psiRasterCx6i','psiRasterNRT','psiRasterNRT2','psiRasterTC','psiRasterTC2',...
            'psi2RasterCx23mean','psi2RasterCx23CI95','psi2RasterCx23imean','psi2RasterCx23iCI95',...
            'psi2RasterCx4mean','psi2RasterCx4CI95','psi2RasterCx4imean','psi2RasterCx4iCI95',...
            'psi2RasterCx5mean','psi2RasterCx5CI95','psi2RasterCx5imean','psi2RasterCx5iCI95',...
            'psi2RasterCx6mean','psi2RasterCx6CI95','psi2RasterCx6imean','psi2RasterCx6iCI95',...
            'psi2RasterNRTmean','psi2RasterNRTCI95','psi2RasterNRT2mean','psi2RasterNRT2CI95',...
            'psi2RasterTCmean','psi2RasterTCCI95','psi2RasterTC2mean','psi2RasterTC2CI95',...
            'psi2RasterCx23MeanAligned','psi2RasterCx23CI95Aligned','psi2RasterCx23iMeanAligned','psi2RasterCx23iCI95Aligned',...
            'psi2RasterCx4MeanAligned','psi2RasterCx4CI95Aligned','psi2RasterCx4iMeanAligned','psi2RasterCx4iCI95Aligned',...
            'psi2RasterCx5MeanAligned','psi2RasterCx5CI95Aligned','psi2RasterCx5iMeanAligned','psi2RasterCx5iCI95Aligned',...
            'psi2RasterCx6MeanAligned','psi2RasterCx6CI95Aligned','psi2RasterCx6iMeanAligned','psi2RasterCx6iCI95Aligned',...
            'psi2RasterNRTMeanAligned','psi2RasterNRTCI95Aligned','psi2RasterNRT2MeanAligned','psi2RasterNRT2CI95Aligned',...
            'psi2RasterTCMeanAligned','psi2RasterTCCI95Aligned','psi2RasterTC2MeanAligned','psi2RasterTC2CI95Aligned',...
            'psi2RasterCx23MeanAlignedScaled','psi2RasterCx23CI95AlignedScaled','psi2RasterCx23iMeanAlignedScaled','psi2RasterCx23iCI95AlignedScaled',...
            'psi2RasterCx4MeanAlignedScaled','psi2RasterCx4CI95AlignedScaled','psi2RasterCx4iMeanAlignedScaled','psi2RasterCx4iCI95AlignedScaled',...
            'psi2RasterCx5MeanAlignedScaled','psi2RasterCx5CI95AlignedScaled','psi2RasterCx5iMeanAlignedScaled','psi2RasterCx5iCI95AlignedScaled',...
            'psi2RasterCx6MeanAlignedScaled','psi2RasterCx6CI95AlignedScaled','psi2RasterCx6iMeanAlignedScaled','psi2RasterCx6iCI95AlignedScaled',...
            'psi2RasterNRTMeanAlignedScaled','psi2RasterNRTCI95AlignedScaled','psi2RasterNRT2MeanAlignedScaled','psi2RasterNRT2CI95AlignedScaled',...
            'psi2RasterTCMeanAlignedScaled','psi2RasterTCCI95AlignedScaled','psi2RasterTC2MeanAlignedScaled','psi2RasterTC2CI95AlignedScaled',...
            'psi2RasterCx23MeanAlignedLarge','psi2RasterCx23CI95AlignedLarge','psi2RasterCx23iMeanAlignedLarge','psi2RasterCx23iCI95AlignedLarge',...
            'psi2RasterCx4MeanAlignedLarge','psi2RasterCx4CI95AlignedLarge','psi2RasterCx4iMeanAlignedLarge','psi2RasterCx4iCI95AlignedLarge',...
            'psi2RasterCx5MeanAlignedLarge','psi2RasterCx5CI95AlignedLarge','psi2RasterCx5iMeanAlignedLarge','psi2RasterCx5iCI95AlignedLarge',...
            'psi2RasterCx6MeanAlignedLarge','psi2RasterCx6CI95AlignedLarge','psi2RasterCx6iMeanAlignedLarge','psi2RasterCx6iCI95AlignedLarge',...
            'psi2RasterNRTMeanAlignedLarge','psi2RasterNRTCI95AlignedLarge','psi2RasterNRT2MeanAlignedLarge','psi2RasterNRT2CI95AlignedLarge',...
            'psi2RasterTCMeanAlignedLarge','psi2RasterTCCI95AlignedLarge','psi2RasterTC2MeanAlignedLarge','psi2RasterTC2CI95AlignedLarge',...
            'psi2RasterCx23MeanAlignedScaledLarge','psi2RasterCx23CI95AlignedScaledLarge','psi2RasterCx23iMeanAlignedScaledLarge','psi2RasterCx23iCI95AlignedScaledLarge',...
            'psi2RasterCx4MeanAlignedScaledLarge','psi2RasterCx4CI95AlignedScaledLarge','psi2RasterCx4iMeanAlignedScaledLarge','psi2RasterCx4iCI95AlignedScaledLarge',...
            'psi2RasterCx5MeanAlignedScaledLarge','psi2RasterCx5CI95AlignedScaledLarge','psi2RasterCx5iMeanAlignedScaledLarge','psi2RasterCx5iCI95AlignedScaledLarge',...
            'psi2RasterCx6MeanAlignedScaledLarge','psi2RasterCx6CI95AlignedScaledLarge','psi2RasterCx6iMeanAlignedScaledLarge','psi2RasterCx6iCI95AlignedScaledLarge',...
            'psi2RasterNRTMeanAlignedScaledLarge','psi2RasterNRTCI95AlignedScaledLarge','psi2RasterNRT2MeanAlignedScaledLarge','psi2RasterNRT2CI95AlignedScaledLarge',...
            'psi2RasterTCMeanAlignedScaledLarge','psi2RasterTCCI95AlignedScaledLarge','psi2RasterTC2MeanAlignedScaledLarge','psi2RasterTC2CI95AlignedScaledLarge',...
            'tStartAligned','tEndAligned','tStartAlignedLarge','tEndAlignedLarge',...
            'tStartAlignedScaled','tEndAlignedScaled','tStartAlignedScaledLarge','tEndAlignedScaledLarge',...
            'psi2RasterCx23MeanAligned_i','psi2RasterCx23CI95Aligned_i','psi2RasterCx23iMeanAligned_i','psi2RasterCx23iCI95Aligned_i',...
            'psi2RasterCx4MeanAligned_i','psi2RasterCx4CI95Aligned_i','psi2RasterCx4iMeanAligned_i','psi2RasterCx4iCI95Aligned_i',...
            'psi2RasterCx5MeanAligned_i','psi2RasterCx5CI95Aligned_i','psi2RasterCx5iMeanAligned_i','psi2RasterCx5iCI95Aligned_i',...
            'psi2RasterCx6MeanAligned_i','psi2RasterCx6CI95Aligned_i','psi2RasterCx6iMeanAligned_i','psi2RasterCx6iCI95Aligned_i',...
            'psi2RasterNRTMeanAligned_i','psi2RasterNRTCI95Aligned_i','psi2RasterNRT2MeanAligned_i','psi2RasterNRT2CI95Aligned_i',...
            'psi2RasterTCMeanAligned_i','psi2RasterTCCI95Aligned_i','psi2RasterTC2MeanAligned_i','psi2RasterTC2CI95Aligned_i',...
            'psi2RasterCx23MeanAlignedScaled_i','psi2RasterCx23CI95AlignedScaled_i','psi2RasterCx23iMeanAlignedScaled_i','psi2RasterCx23iCI95AlignedScaled_i',...
            'psi2RasterCx4MeanAlignedScaled_i','psi2RasterCx4CI95AlignedScaled_i','psi2RasterCx4iMeanAlignedScaled_i','psi2RasterCx4iCI95AlignedScaled_i',...
            'psi2RasterCx5MeanAlignedScaled_i','psi2RasterCx5CI95AlignedScaled_i','psi2RasterCx5iMeanAlignedScaled_i','psi2RasterCx5iCI95AlignedScaled_i',...
            'psi2RasterCx6MeanAlignedScaled_i','psi2RasterCx6CI95AlignedScaled_i','psi2RasterCx6iMeanAlignedScaled_i','psi2RasterCx6iCI95AlignedScaled_i',...
            'psi2RasterNRTMeanAlignedScaled_i','psi2RasterNRTCI95AlignedScaled_i','psi2RasterNRT2MeanAlignedScaled_i','psi2RasterNRT2CI95AlignedScaled_i',...
            'psi2RasterTCMeanAlignedScaled_i','psi2RasterTCCI95AlignedScaled_i','psi2RasterTC2MeanAlignedScaled_i','psi2RasterTC2CI95AlignedScaled_i',...
            'psi2RasterCx23MeanAlignedLarge_i','psi2RasterCx23CI95AlignedLarge_i','psi2RasterCx23iMeanAlignedLarge_i','psi2RasterCx23iCI95AlignedLarge_i',...
            'psi2RasterCx4MeanAlignedLarge_i','psi2RasterCx4CI95AlignedLarge_i','psi2RasterCx4iMeanAlignedLarge_i','psi2RasterCx4iCI95AlignedLarge_i',...
            'psi2RasterCx5MeanAlignedLarge_i','psi2RasterCx5CI95AlignedLarge_i','psi2RasterCx5iMeanAlignedLarge_i','psi2RasterCx5iCI95AlignedLarge_i',...
            'psi2RasterCx6MeanAlignedLarge_i','psi2RasterCx6CI95AlignedLarge_i','psi2RasterCx6iMeanAlignedLarge_i','psi2RasterCx6iCI95AlignedLarge_i',...
            'psi2RasterNRTMeanAlignedLarge_i','psi2RasterNRTCI95AlignedLarge_i','psi2RasterNRT2MeanAlignedLarge_i','psi2RasterNRT2CI95AlignedLarge_i',...
            'psi2RasterTCMeanAlignedLarge_i','psi2RasterTCCI95AlignedLarge_i','psi2RasterTC2MeanAlignedLarge_i','psi2RasterTC2CI95AlignedLarge_i',...
            'psi2RasterCx23MeanAlignedScaledLarge_i','psi2RasterCx23CI95AlignedScaledLarge_i','psi2RasterCx23iMeanAlignedScaledLarge_i','psi2RasterCx23iCI95AlignedScaledLarge_i',...
            'psi2RasterCx4MeanAlignedScaledLarge_i','psi2RasterCx4CI95AlignedScaledLarge_i','psi2RasterCx4iMeanAlignedScaledLarge_i','psi2RasterCx4iCI95AlignedScaledLarge_i',...
            'psi2RasterCx5MeanAlignedScaledLarge_i','psi2RasterCx5CI95AlignedScaledLarge_i','psi2RasterCx5iMeanAlignedScaledLarge_i','psi2RasterCx5iCI95AlignedScaledLarge_i',...
            'psi2RasterCx6MeanAlignedScaledLarge_i','psi2RasterCx6CI95AlignedScaledLarge_i','psi2RasterCx6iMeanAlignedScaledLarge_i','psi2RasterCx6iCI95AlignedScaledLarge_i',...
            'psi2RasterNRTMeanAlignedScaledLarge_i','psi2RasterNRTCI95AlignedScaledLarge_i','psi2RasterNRT2MeanAlignedScaledLarge_i','psi2RasterNRT2CI95AlignedScaledLarge_i',...
            'psi2RasterTCMeanAlignedScaledLarge_i','psi2RasterTCCI95AlignedScaledLarge_i','psi2RasterTC2MeanAlignedScaledLarge_i','psi2RasterTC2CI95AlignedScaledLarge_i',...
            'psi2RasterMeanAlignedScaled','psi2RasterCI95AlignedScaled', 'psi2RasterMeanAlignedScaled_i','psi2RasterCI95AlignedScaled_i',...
            'tStartAligned_i','tEndAligned_i','tStartAlignedLarge_i','tEndAlignedLarge_i',...
            'tStartAlignedScaled_i','tEndAlignedScaled_i','tStartAlignedScaledLarge_i','tEndAlignedScaledLarge_i',...
            'iRange','nIN','nNRT','nPY','nTC','psiWindow');
    elseif voltage && spiking
        save('psiData2.mat', 'dt','t','dtInterpInit','dtInterpFinal','tInterpInit','tInterpFinal',...
            'psiCx23','psiCx23i','psiCx4','psiCx4i','psiCx5','psiCx5i',...
            'psiCx6','psiCx6i','psiNRT','psiNRT2','psiTC','psiTC2',...
            'psiRasterCx23','psiRasterCx23i','psiRasterCx4','psiRasterCx4i','psiRasterCx5','psiRasterCx5i',...
            'psiRasterCx6','psiRasterCx6i','psiRasterNRT','psiRasterNRT2','psiRasterTC','psiRasterTC2',...
            'psi2Cx23mean','psi2Cx23CI95','psi2Cx23imean','psi2Cx23iCI95',...
            'psi2Cx4mean','psi2Cx4CI95','psi2Cx4imean','psi2Cx4iCI95',...
            'psi2Cx5mean','psi2Cx5CI95','psi2Cx5imean','psi2Cx5iCI95',...
            'psi2Cx6mean','psi2Cx6CI95','psi2Cx6imean','psi2Cx6iCI95',...
            'psi2NRTmean','psi2NRTCI95','psi2NRT2mean','psi2NRT2CI95',...
            'psi2TCmean','psi2TCCI95','psi2TC2mean','psi2TC2CI95',...
            'psi2RasterCx23mean','psi2RasterCx23CI95','psi2RasterCx23imean','psi2RasterCx23iCI95',...
            'psi2RasterCx4mean','psi2RasterCx4CI95','psi2RasterCx4imean','psi2RasterCx4iCI95',...
            'psi2RasterCx5mean','psi2RasterCx5CI95','psi2RasterCx5imean','psi2RasterCx5iCI95',...
            'psi2RasterCx6mean','psi2RasterCx6CI95','psi2RasterCx6imean','psi2RasterCx6iCI95',...
            'psi2RasterNRTmean','psi2RasterNRTCI95','psi2RasterNRT2mean','psi2RasterNRT2CI95',...
            'psi2RasterTCmean','psi2RasterTCCI95','psi2RasterTC2mean','psi2RasterTC2CI95',...
            'psi2Cx23MeanAligned','psi2Cx23CI95Aligned','psi2Cx23iMeanAligned','psi2Cx23iCI95Aligned',...
            'psi2Cx4MeanAligned','psi2Cx4CI95Aligned','psi2Cx4iMeanAligned','psi2Cx4iCI95Aligned',...
            'psi2Cx5MeanAligned','psi2Cx5CI95Aligned','psi2Cx5iMeanAligned','psi2Cx5iCI95Aligned',...
            'psi2Cx6MeanAligned','psi2Cx6CI95Aligned','psi2Cx6iMeanAligned','psi2Cx6iCI95Aligned',...
            'psi2NRTMeanAligned','psi2NRTCI95Aligned','psi2NRT2MeanAligned','psi2NRT2CI95Aligned',...
            'psi2TCMeanAligned','psi2TCCI95Aligned','psi2TC2MeanAligned','psi2TC2CI95Aligned',...
            'psi2RasterCx23MeanAligned','psi2RasterCx23CI95Aligned','psi2RasterCx23iMeanAligned','psi2RasterCx23iCI95Aligned',...
            'psi2RasterCx4MeanAligned','psi2RasterCx4CI95Aligned','psi2RasterCx4iMeanAligned','psi2RasterCx4iCI95Aligned',...
            'psi2RasterCx5MeanAligned','psi2RasterCx5CI95Aligned','psi2RasterCx5iMeanAligned','psi2RasterCx5iCI95Aligned',...
            'psi2RasterCx6MeanAligned','psi2RasterCx6CI95Aligned','psi2RasterCx6iMeanAligned','psi2RasterCx6iCI95Aligned',...
            'psi2RasterNRTMeanAligned','psi2RasterNRTCI95Aligned','psi2RasterNRT2MeanAligned','psi2RasterNRT2CI95Aligned',...
            'psi2RasterTCMeanAligned','psi2RasterTCCI95Aligned','psi2RasterTC2MeanAligned','psi2RasterTC2CI95Aligned',...
            'psi2Cx23MeanAlignedScaled','psi2Cx23CI95AlignedScaled','psi2Cx23iMeanAlignedScaled','psi2Cx23iCI95AlignedScaled',...
            'psi2Cx4MeanAlignedScaled','psi2Cx4CI95AlignedScaled','psi2Cx4iMeanAlignedScaled','psi2Cx4iCI95AlignedScaled',...
            'psi2Cx5MeanAlignedScaled','psi2Cx5CI95AlignedScaled','psi2Cx5iMeanAlignedScaled','psi2Cx5iCI95AlignedScaled',...
            'psi2Cx6MeanAlignedScaled','psi2Cx6CI95AlignedScaled','psi2Cx6iMeanAlignedScaled','psi2Cx6iCI95AlignedScaled',...
            'psi2NRTMeanAlignedScaled','psi2NRTCI95AlignedScaled','psi2NRT2MeanAlignedScaled','psi2NRT2CI95AlignedScaled',...
            'psi2TCMeanAlignedScaled','psi2TCCI95AlignedScaled','psi2TC2MeanAlignedScaled','psi2TC2CI95AlignedScaled',...
            'psi2RasterCx23MeanAlignedScaled','psi2RasterCx23CI95AlignedScaled','psi2RasterCx23iMeanAlignedScaled','psi2RasterCx23iCI95AlignedScaled',...
            'psi2RasterCx4MeanAlignedScaled','psi2RasterCx4CI95AlignedScaled','psi2RasterCx4iMeanAlignedScaled','psi2RasterCx4iCI95AlignedScaled',...
            'psi2RasterCx5MeanAlignedScaled','psi2RasterCx5CI95AlignedScaled','psi2RasterCx5iMeanAlignedScaled','psi2RasterCx5iCI95AlignedScaled',...
            'psi2RasterCx6MeanAlignedScaled','psi2RasterCx6CI95AlignedScaled','psi2RasterCx6iMeanAlignedScaled','psi2RasterCx6iCI95AlignedScaled',...
            'psi2RasterNRTMeanAlignedScaled','psi2RasterNRTCI95AlignedScaled','psi2RasterNRT2MeanAlignedScaled','psi2RasterNRT2CI95AlignedScaled',...
            'psi2RasterTCMeanAlignedScaled','psi2RasterTCCI95AlignedScaled','psi2RasterTC2MeanAlignedScaled','psi2RasterTC2CI95AlignedScaled',...
            'psi2Cx23MeanAlignedLarge','psi2Cx23CI95AlignedLarge','psi2Cx23iMeanAlignedLarge','psi2Cx23iCI95AlignedLarge',...
            'psi2Cx4MeanAlignedLarge','psi2Cx4CI95AlignedLarge','psi2Cx4iMeanAlignedLarge','psi2Cx4iCI95AlignedLarge',...
            'psi2Cx5MeanAlignedLarge','psi2Cx5CI95AlignedLarge','psi2Cx5iMeanAlignedLarge','psi2Cx5iCI95AlignedLarge',...
            'psi2Cx6MeanAlignedLarge','psi2Cx6CI95AlignedLarge','psi2Cx6iMeanAlignedLarge','psi2Cx6iCI95AlignedLarge',...
            'psi2NRTMeanAlignedLarge','psi2NRTCI95AlignedLarge','psi2NRT2MeanAlignedLarge','psi2NRT2CI95AlignedLarge',...
            'psi2TCMeanAlignedLarge','psi2TCCI95AlignedLarge','psi2TC2MeanAlignedLarge','psi2TC2CI95AlignedLarge',...
            'psi2RasterCx23MeanAlignedLarge','psi2RasterCx23CI95AlignedLarge','psi2RasterCx23iMeanAlignedLarge','psi2RasterCx23iCI95AlignedLarge',...
            'psi2RasterCx4MeanAlignedLarge','psi2RasterCx4CI95AlignedLarge','psi2RasterCx4iMeanAlignedLarge','psi2RasterCx4iCI95AlignedLarge',...
            'psi2RasterCx5MeanAlignedLarge','psi2RasterCx5CI95AlignedLarge','psi2RasterCx5iMeanAlignedLarge','psi2RasterCx5iCI95AlignedLarge',...
            'psi2RasterCx6MeanAlignedLarge','psi2RasterCx6CI95AlignedLarge','psi2RasterCx6iMeanAlignedLarge','psi2RasterCx6iCI95AlignedLarge',...
            'psi2RasterNRTMeanAlignedLarge','psi2RasterNRTCI95AlignedLarge','psi2RasterNRT2MeanAlignedLarge','psi2RasterNRT2CI95AlignedLarge',...
            'psi2RasterTCMeanAlignedLarge','psi2RasterTCCI95AlignedLarge','psi2RasterTC2MeanAlignedLarge','psi2RasterTC2CI95AlignedLarge',...
            'psi2Cx23MeanAlignedScaledLarge','psi2Cx23CI95AlignedScaledLarge','psi2Cx23iMeanAlignedScaledLarge','psi2Cx23iCI95AlignedScaledLarge',...
            'psi2Cx4MeanAlignedScaledLarge','psi2Cx4CI95AlignedScaledLarge','psi2Cx4iMeanAlignedScaledLarge','psi2Cx4iCI95AlignedScaledLarge',...
            'psi2Cx5MeanAlignedScaledLarge','psi2Cx5CI95AlignedScaledLarge','psi2Cx5iMeanAlignedScaledLarge','psi2Cx5iCI95AlignedScaledLarge',...
            'psi2Cx6MeanAlignedScaledLarge','psi2Cx6CI95AlignedScaledLarge','psi2Cx6iMeanAlignedScaledLarge','psi2Cx6iCI95AlignedScaledLarge',...
            'psi2NRTMeanAlignedScaledLarge','psi2NRTCI95AlignedScaledLarge','psi2NRT2MeanAlignedScaledLarge','psi2NRT2CI95AlignedScaledLarge',...
            'psi2TCMeanAlignedScaledLarge','psi2TCCI95AlignedScaledLarge','psi2TC2MeanAlignedScaledLarge','psi2TC2CI95AlignedScaledLarge',...
            'psi2RasterCx23MeanAlignedScaledLarge','psi2RasterCx23CI95AlignedScaledLarge','psi2RasterCx23iMeanAlignedScaledLarge','psi2RasterCx23iCI95AlignedScaledLarge',...
            'psi2RasterCx4MeanAlignedScaledLarge','psi2RasterCx4CI95AlignedScaledLarge','psi2RasterCx4iMeanAlignedScaledLarge','psi2RasterCx4iCI95AlignedScaledLarge',...
            'psi2RasterCx5MeanAlignedScaledLarge','psi2RasterCx5CI95AlignedScaledLarge','psi2RasterCx5iMeanAlignedScaledLarge','psi2RasterCx5iCI95AlignedScaledLarge',...
            'psi2RasterCx6MeanAlignedScaledLarge','psi2RasterCx6CI95AlignedScaledLarge','psi2RasterCx6iMeanAlignedScaledLarge','psi2RasterCx6iCI95AlignedScaledLarge',...
            'psi2RasterNRTMeanAlignedScaledLarge','psi2RasterNRTCI95AlignedScaledLarge','psi2RasterNRT2MeanAlignedScaledLarge','psi2RasterNRT2CI95AlignedScaledLarge',...
            'psi2RasterTCMeanAlignedScaledLarge','psi2RasterTCCI95AlignedScaledLarge','psi2RasterTC2MeanAlignedScaledLarge','psi2RasterTC2CI95AlignedScaledLarge',...
            'tStartAligned','tEndAligned','tStartAlignedLarge','tEndAlignedLarge',...
            'tStartAlignedScaled_i','tEndAlignedScaled_i','tStartAlignedScaledLarge_i','tEndAlignedScaledLarge_i',...
            'psi2Cx23MeanAligned_i','psi2Cx23CI95Aligned_i','psi2Cx23iMeanAligned_i','psi2Cx23iCI95Aligned_i',...
            'psi2Cx4MeanAligned_i','psi2Cx4CI95Aligned_i','psi2Cx4iMeanAligned_i','psi2Cx4iCI95Aligned_i',...
            'psi2Cx5MeanAligned_i','psi2Cx5CI95Aligned_i','psi2Cx5iMeanAligned_i','psi2Cx5iCI95Aligned_i',...
            'psi2Cx6MeanAligned_i','psi2Cx6CI95Aligned_i','psi2Cx6iMeanAligned_i','psi2Cx6iCI95Aligned_i',...
            'psi2NRTMeanAligned_i','psi2NRTCI95Aligned_i','psi2NRT2MeanAligned_i','psi2NRT2CI95Aligned_i',...
            'psi2TCMeanAligned_i','psi2TCCI95Aligned_i','psi2TC2MeanAligned_i','psi2TC2CI95Aligned_i',...
            'psi2RasterCx23MeanAligned_i','psi2RasterCx23CI95Aligned_i','psi2RasterCx23iMeanAligned_i','psi2RasterCx23iCI95Aligned_i',...
            'psi2RasterCx4MeanAligned_i','psi2RasterCx4CI95Aligned_i','psi2RasterCx4iMeanAligned_i','psi2RasterCx4iCI95Aligned_i',...
            'psi2RasterCx5MeanAligned_i','psi2RasterCx5CI95Aligned_i','psi2RasterCx5iMeanAligned_i','psi2RasterCx5iCI95Aligned_i',...
            'psi2RasterCx6MeanAligned_i','psi2RasterCx6CI95Aligned_i','psi2RasterCx6iMeanAligned_i','psi2RasterCx6iCI95Aligned_i',...
            'psi2RasterNRTMeanAligned_i','psi2RasterNRTCI95Aligned_i','psi2RasterNRT2MeanAligned_i','psi2RasterNRT2CI95Aligned_i',...
            'psi2RasterTCMeanAligned_i','psi2RasterTCCI95Aligned_i','psi2RasterTC2MeanAligned_i','psi2RasterTC2CI95Aligned_i',...
            'psi2Cx23MeanAlignedScaled_i','psi2Cx23CI95AlignedScaled_i','psi2Cx23iMeanAlignedScaled_i','psi2Cx23iCI95AlignedScaled_i',...
            'psi2Cx4MeanAlignedScaled_i','psi2Cx4CI95AlignedScaled_i','psi2Cx4iMeanAlignedScaled_i','psi2Cx4iCI95AlignedScaled_i',...
            'psi2Cx5MeanAlignedScaled_i','psi2Cx5CI95AlignedScaled_i','psi2Cx5iMeanAlignedScaled_i','psi2Cx5iCI95AlignedScaled_i',...
            'psi2Cx6MeanAlignedScaled_i','psi2Cx6CI95AlignedScaled_i','psi2Cx6iMeanAlignedScaled_i','psi2Cx6iCI95AlignedScaled_i',...
            'psi2NRTMeanAlignedScaled_i','psi2NRTCI95AlignedScaled_i','psi2NRT2MeanAlignedScaled_i','psi2NRT2CI95AlignedScaled_i',...
            'psi2TCMeanAlignedScaled_i','psi2TCCI95AlignedScaled_i','psi2TC2MeanAlignedScaled_i','psi2TC2CI95AlignedScaled_i',...
            'psi2RasterCx23MeanAlignedScaled_i','psi2RasterCx23CI95AlignedScaled_i','psi2RasterCx23iMeanAlignedScaled_i','psi2RasterCx23iCI95AlignedScaled_i',...
            'psi2RasterCx4MeanAlignedScaled_i','psi2RasterCx4CI95AlignedScaled_i','psi2RasterCx4iMeanAlignedScaled_i','psi2RasterCx4iCI95AlignedScaled_i',...
            'psi2RasterCx5MeanAlignedScaled_i','psi2RasterCx5CI95AlignedScaled_i','psi2RasterCx5iMeanAlignedScaled_i','psi2RasterCx5iCI95AlignedScaled_i',...
            'psi2RasterCx6MeanAlignedScaled_i','psi2RasterCx6CI95AlignedScaled_i','psi2RasterCx6iMeanAlignedScaled_i','psi2RasterCx6iCI95AlignedScaled_i',...
            'psi2RasterNRTMeanAlignedScaled_i','psi2RasterNRTCI95AlignedScaled_i','psi2RasterNRT2MeanAlignedScaled_i','psi2RasterNRT2CI95AlignedScaled_i',...
            'psi2RasterTCMeanAlignedScaled_i','psi2RasterTCCI95AlignedScaled_i','psi2RasterTC2MeanAlignedScaled_i','psi2RasterTC2CI95AlignedScaled_i',...
            'psi2Cx23MeanAlignedLarge_i','psi2Cx23CI95AlignedLarge_i','psi2Cx23iMeanAlignedLarge_i','psi2Cx23iCI95AlignedLarge_i',...
            'psi2Cx4MeanAlignedLarge_i','psi2Cx4CI95AlignedLarge_i','psi2Cx4iMeanAlignedLarge_i','psi2Cx4iCI95AlignedLarge_i',...
            'psi2Cx5MeanAlignedLarge_i','psi2Cx5CI95AlignedLarge_i','psi2Cx5iMeanAlignedLarge_i','psi2Cx5iCI95AlignedLarge_i',...
            'psi2Cx6MeanAlignedLarge_i','psi2Cx6CI95AlignedLarge_i','psi2Cx6iMeanAlignedLarge_i','psi2Cx6iCI95AlignedLarge_i',...
            'psi2NRTMeanAlignedLarge_i','psi2NRTCI95AlignedLarge_i','psi2NRT2MeanAlignedLarge_i','psi2NRT2CI95AlignedLarge_i',...
            'psi2TCMeanAlignedLarge_i','psi2TCCI95AlignedLarge_i','psi2TC2MeanAlignedLarge_i','psi2TC2CI95AlignedLarge_i',...
            'psi2RasterCx23MeanAlignedLarge_i','psi2RasterCx23CI95AlignedLarge_i','psi2RasterCx23iMeanAlignedLarge_i','psi2RasterCx23iCI95AlignedLarge_i',...
            'psi2RasterCx4MeanAlignedLarge_i','psi2RasterCx4CI95AlignedLarge_i','psi2RasterCx4iMeanAlignedLarge_i','psi2RasterCx4iCI95AlignedLarge_i',...
            'psi2RasterCx5MeanAlignedLarge_i','psi2RasterCx5CI95AlignedLarge_i','psi2RasterCx5iMeanAlignedLarge_i','psi2RasterCx5iCI95AlignedLarge_i',...
            'psi2RasterCx6MeanAlignedLarge_i','psi2RasterCx6CI95AlignedLarge_i','psi2RasterCx6iMeanAlignedLarge_i','psi2RasterCx6iCI95AlignedLarge_i',...
            'psi2RasterNRTMeanAlignedLarge_i','psi2RasterNRTCI95AlignedLarge_i','psi2RasterNRT2MeanAlignedLarge_i','psi2RasterNRT2CI95AlignedLarge_i',...
            'psi2RasterTCMeanAlignedLarge_i','psi2RasterTCCI95AlignedLarge_i','psi2RasterTC2MeanAlignedLarge_i','psi2RasterTC2CI95AlignedLarge_i',...
            'psi2Cx23MeanAlignedScaledLarge_i','psi2Cx23CI95AlignedScaledLarge_i','psi2Cx23iMeanAlignedScaledLarge_i','psi2Cx23iCI95AlignedScaledLarge_i',...
            'psi2Cx4MeanAlignedScaledLarge_i','psi2Cx4CI95AlignedScaledLarge_i','psi2Cx4iMeanAlignedScaledLarge_i','psi2Cx4iCI95AlignedScaledLarge_i',...
            'psi2Cx5MeanAlignedScaledLarge_i','psi2Cx5CI95AlignedScaledLarge_i','psi2Cx5iMeanAlignedScaledLarge_i','psi2Cx5iCI95AlignedScaledLarge_i',...
            'psi2Cx6MeanAlignedScaledLarge_i','psi2Cx6CI95AlignedScaledLarge_i','psi2Cx6iMeanAlignedScaledLarge_i','psi2Cx6iCI95AlignedScaledLarge_i',...
            'psi2NRTMeanAlignedScaledLarge_i','psi2NRTCI95AlignedScaledLarge_i','psi2NRT2MeanAlignedScaledLarge_i','psi2NRT2CI95AlignedScaledLarge_i',...
            'psi2TCMeanAlignedScaledLarge_i','psi2TCCI95AlignedScaledLarge_i','psi2TC2MeanAlignedScaledLarge_i','psi2TC2CI95AlignedScaledLarge_i',...
            'psi2RasterCx23MeanAlignedScaledLarge_i','psi2RasterCx23CI95AlignedScaledLarge_i','psi2RasterCx23iMeanAlignedScaledLarge_i','psi2RasterCx23iCI95AlignedScaledLarge_i',...
            'psi2RasterCx4MeanAlignedScaledLarge_i','psi2RasterCx4CI95AlignedScaledLarge_i','psi2RasterCx4iMeanAlignedScaledLarge_i','psi2RasterCx4iCI95AlignedScaledLarge_i',...
            'psi2RasterCx5MeanAlignedScaledLarge_i','psi2RasterCx5CI95AlignedScaledLarge_i','psi2RasterCx5iMeanAlignedScaledLarge_i','psi2RasterCx5iCI95AlignedScaledLarge_i',...
            'psi2RasterCx6MeanAlignedScaledLarge_i','psi2RasterCx6CI95AlignedScaledLarge_i','psi2RasterCx6iMeanAlignedScaledLarge_i','psi2RasterCx6iCI95AlignedScaledLarge_i',...
            'psi2RasterNRTMeanAlignedScaledLarge_i','psi2RasterNRTCI95AlignedScaledLarge_i','psi2RasterNRT2MeanAlignedScaledLarge_i','psi2RasterNRT2CI95AlignedScaledLarge_i',...
            'psi2RasterTCMeanAlignedScaledLarge_i','psi2RasterTCCI95AlignedScaledLarge_i','psi2RasterTC2MeanAlignedScaledLarge_i','psi2RasterTC2CI95AlignedScaledLarge_i',...
            'psi2MeanAlignedScaled','psi2CI95AlignedScaled', 'psi2MeanAlignedScaled_i','psi2CI95AlignedScaled_i',...
            'psi2RasterMeanAlignedScaled','psi2RasterCI95AlignedScaled', 'psi2RasterMeanAlignedScaled_i','psi2RasterCI95AlignedScaled_i',...
            'tStartAligned_i','tEndAligned_i','tStartAlignedLarge_i','tEndAlignedLarge_i',...
            'tStartAlignedScaled_i','tEndAlignedScaled_i','tStartAlignedScaledLarge_i','tEndAlignedScaledLarge_i',...
            'iRange','nIN','nNRT','nPY','nTC','psiWindow');
    end
else
    load('psiData2.mat'); %#ok<*UNRCH>
end

if ~fullRun
    if voltage
        colours = [cellColour('Cx23'); cellColour('Cx23'); cellColour('Cx4'); cellColour('Cx4'); cellColour('Cx5'); cellColour('Cx5');...
            cellColour('Cx6'); cellColour('Cx6'); cellColour('NRT'); cellColour('NRT2'); cellColour('TC'); cellColour('TC2')];
        lineTypes = {'-','--','-','--','-','--','-','--','-','-','-','-'};
        legendEntries = {'L2/3 PY', 'L2/3 IN', 'L4 PY', 'L4 IN', 'L5 PY', 'L5 IN', 'L6 PY', 'L6 IN', 'NRT_F_O', 'NRT_H_O', 'TC_F_O', 'TC_H_O'};
        fPSI2 = frAlignPlot(psi2MeanAlignedScaled, psi2CI95AlignedScaled, tStartAlignedScaled, tEndAlignedScaled, colours, lineTypes, 'PSI',...
            legendEntries, 'V_M PSI2');
        fPSI2_i = frAlignPlot(psi2MeanAlignedScaled_i, psi2CI95AlignedScaled_i, tStartAlignedScaled_i, tEndAlignedScaled_i, colours, lineTypes, 'PSI',...
            legendEntries, 'V_M PSI2');
    end
    
    if spiking
        colours = [cellColour('Cx23'); cellColour('Cx23'); cellColour('Cx4'); cellColour('Cx4'); cellColour('Cx5'); cellColour('Cx5');...
            cellColour('Cx6'); cellColour('Cx6'); cellColour('NRT'); cellColour('NRT2'); cellColour('TC'); cellColour('TC2')];
        lineTypes = {'-','--','-','--','-','--','-','--','-','-','-','-'};
        legendEntries = {'L2/3 PY', 'L2/3 IN', 'L4 PY', 'L4 IN', 'L5 PY', 'L5 IN', 'L6 PY', 'L6 IN', 'NRT_F_O', 'NRT_H_O', 'TC_F_O', 'TC_H_O'};
        fPSI2Raster = frAlignPlot(psi2RasterMeanAlignedScaled, psi2RasterCI95AlignedScaled, tStartAlignedScaled, tEndAlignedScaled,...
            colours, lineTypes, 'PSI', legendEntries, 'Spiking PSI2');
        fPSI2Raster_i = frAlignPlot(psi2RasterMeanAlignedScaled_i, psi2RasterCI95AlignedScaled_i, tStartAlignedScaled_i, tEndAlignedScaled_i,...
            colours, lineTypes, 'PSI', legendEntries, 'Spiking PSI2');
    end
end
toc