function d = designFilterBP(Fpass, Astop1, Apass, Astop2, Fs)
% A helper function of AnHT for designing Buterworth bandpass filters.

d = designfilt('bandpassiir', ...
	'StopbandFrequency1',Fpass(1,1), 'PassbandFrequency1',Fpass(2,1), ...
  'PassbandFrequency2',Fpass(4,1), 'StopbandFrequency2',Fpass(5,1), ...
  'StopbandAttenuation1',Astop1, 'PassbandRipple',Apass, ...
  'StopbandAttenuation2',Astop2, 'DesignMethod','butter', 'SampleRate',Fs);
end